import { ReferenceStruct } from "./core.js";
import { ImVec2 } from "./imgui.js";
export type ImNodesCol = number;
export type ImNodesStyleVar = number;
export type ImNodesStyleFlags = number;
export type ImNodesPinShape = number;
export type ImNodesAttributeFlags = number;
export type ImNodesMiniMapLocation = number;
export declare class ImNodesContext extends ReferenceStruct {
}
export declare class ImNodesEditorContext extends ReferenceStruct {
}
export declare class ImNodesIO extends ReferenceStruct {
    get AltMouseButton(): number;
    set AltMouseButton(v: number);
    get AutoPanningSpeed(): number;
    set AutoPanningSpeed(v: number);
}
export declare class ImNodesStyle extends ReferenceStruct {
    get GridSpacing(): number;
    set GridSpacing(v: number);
    get NodeCornerRounding(): number;
    set NodeCornerRounding(v: number);
    get NodePadding(): ImVec2;
    set NodePadding(v: ImVec2);
    get NodeBorderThickness(): number;
    set NodeBorderThickness(v: number);
    get LinkThickness(): number;
    set LinkThickness(v: number);
    get LinkLineSegmentsPerLength(): number;
    set LinkLineSegmentsPerLength(v: number);
    get LinkHoverDistance(): number;
    set LinkHoverDistance(v: number);
    get PinCircleRadius(): number;
    set PinCircleRadius(v: number);
    get PinQuadSideLength(): number;
    set PinQuadSideLength(v: number);
    get PinTriangleSideLength(): number;
    set PinTriangleSideLength(v: number);
    get PinLineThickness(): number;
    set PinLineThickness(v: number);
    get PinHoverRadius(): number;
    set PinHoverRadius(v: number);
    get PinOffset(): number;
    set PinOffset(v: number);
    get MiniMapPadding(): ImVec2;
    set MiniMapPadding(v: ImVec2);
    get MiniMapOffset(): ImVec2;
    set MiniMapOffset(v: ImVec2);
    get Flags(): ImNodesStyleFlags;
    set Flags(v: ImNodesStyleFlags);
    get Colors(): number[];
    set Colors(v: number[]);
}
export declare const ImNodes: {
    Col: {
        NodeBackground: number;
        NodeBackgroundHovered: number;
        NodeBackgroundSelected: number;
        NodeOutline: number;
        TitleBar: number;
        TitleBarHovered: number;
        TitleBarSelected: number;
        Link: number;
        LinkHovered: number;
        LinkSelected: number;
        Pin: number;
        PinHovered: number;
        BoxSelector: number;
        BoxSelectorOutline: number;
        GridBackground: number;
        GridLine: number;
        GridLinePrimary: number;
        MiniMapBackground: number;
        MiniMapBackgroundHovered: number;
        MiniMapOutline: number;
        MiniMapOutlineHovered: number;
        MiniMapNodeBackground: number;
        MiniMapNodeBackgroundHovered: number;
        MiniMapNodeBackgroundSelected: number;
        MiniMapNodeOutline: number;
        MiniMapLink: number;
        MiniMapLinkSelected: number;
        MiniMapCanvas: number;
        MiniMapCanvasOutline: number;
        COUNT: number;
    };
    StyleVar: {
        GridSpacing: number;
        NodeCornerRounding: number;
        NodePadding: number;
        NodeBorderThickness: number;
        LinkThickness: number;
        LinkLineSegmentsPerLength: number;
        LinkHoverDistance: number;
        PinCircleRadius: number;
        PinQuadSideLength: number;
        PinTriangleSideLength: number;
        PinLineThickness: number;
        PinHoverRadius: number;
        PinOffset: number;
        MiniMapPadding: number;
        MiniMapOffset: number;
        COUNT: number;
    };
    StyleFlags: {
        None: number;
        NodeOutline: number;
        GridLines: number;
        GridLinesPrimary: number;
        GridSnapping: number;
    };
    PinShape: {
        Circle: number;
        CircleFilled: number;
        Triangle: number;
        TriangleFilled: number;
        Quad: number;
        QuadFilled: number;
    };
    AttributeFlags: {
        None: number;
        EnableLinkDetachWithDragClick: number;
        EnableLinkCreationOnSnap: number;
    };
    MiniMapLocation: {
        BottomLeft: number;
        BottomRight: number;
        TopLeft: number;
        TopRight: number;
    };
    CreateContext(): ImNodesContext;
    DestroyContext(ctx?: ImNodesContext | null): void;
    GetCurrentContext(): ImNodesContext;
    SetCurrentContext(ctx: ImNodesContext): void;
    EditorContextCreate(): ImNodesEditorContext;
    EditorContextFree(ctx: ImNodesEditorContext): void;
    EditorContextSet(ctx: ImNodesEditorContext): void;
    EditorContextGetPanning(): ImVec2;
    EditorContextResetPanning(pos: ImVec2): void;
    EditorContextMoveToNode(node_id: number): void;
    GetIO(): ImNodesIO;
    GetStyle(): ImNodesStyle;
    StyleColorsDark(dest?: ImNodesStyle | null): void;
    StyleColorsClassic(dest?: ImNodesStyle | null): void;
    StyleColorsLight(dest?: ImNodesStyle | null): void;
    BeginNodeEditor(): void;
    EndNodeEditor(): void;
    MiniMap(minimap_size_fraction?: number, location?: ImNodesMiniMapLocation): void;
    PushColorStyle(item: ImNodesCol, color: number): void;
    PopColorStyle(): void;
    PushStyleVar(style_item: ImNodesStyleVar, value: number): void;
    PushStyleVarImVec2(style_item: ImNodesStyleVar, value: ImVec2): void;
    PopStyleVar(count?: number): void;
    BeginNode(id: number): void;
    EndNode(): void;
    GetNodeDimensions(id: number): ImVec2;
    BeginNodeTitleBar(): void;
    EndNodeTitleBar(): void;
    BeginInputAttribute(id: number, shape?: ImNodesPinShape): void;
    EndInputAttribute(): void;
    BeginOutputAttribute(id: number, shape?: ImNodesPinShape): void;
    EndOutputAttribute(): void;
    BeginStaticAttribute(id: number): void;
    EndStaticAttribute(): void;
    PushAttributeFlag(flag: ImNodesAttributeFlags): void;
    PopAttributeFlag(): void;
    Link(id: number, start_attribute_id: number, end_attribute_id: number): void;
    SetNodeDraggable(node_id: number, draggable: boolean): void;
    SetNodeScreenSpacePos(node_id: number, screen_space_pos: ImVec2): void;
    SetNodeEditorSpacePos(node_id: number, editor_space_pos: ImVec2): void;
    SetNodeGridSpacePos(node_id: number, grid_space_pos: ImVec2): void;
    GetNodeScreenSpacePos(node_id: number): ImVec2;
    GetNodeEditorSpacePos(node_id: number): ImVec2;
    GetNodeGridSpacePos(node_id: number): ImVec2;
    SnapNodeToGrid(node_id: number): void;
    IsEditorHovered(): boolean;
    IsNodeHovered(node_id: [number]): boolean;
    IsLinkHovered(link_id: [number]): boolean;
    IsPinHovered(attribute_id: [number]): boolean;
    NumSelectedNodes(): number;
    NumSelectedLinks(): number;
    GetSelectedNodes(node_ids: number[]): void;
    GetSelectedLinks(link_ids: number[]): void;
    ClearNodeSelection(): void;
    ClearLinkSelection(): void;
    SelectNode(node_id: number): void;
    ClearNodeSelectionID(node_id: number): void;
    IsNodeSelected(node_id: number): boolean;
    SelectLink(link_id: number): void;
    ClearLinkSelectionID(link_id: number): void;
    IsLinkSelected(link_id: number): boolean;
    IsAttributeActive(): boolean;
    IsAnyAttributeActive(attribute_id?: [number] | null): boolean;
    IsLinkStarted(started_at_attribute_id: [number]): boolean;
    IsLinkDropped(started_at_attribute_id?: [number] | null, including_detached_links?: boolean): boolean;
    IsLinkCreated(started_at_attribute_id?: [number] | null, ended_at_attribute_id?: [number] | null, created_from_snap?: [boolean] | null): boolean;
    IsLinkCreatedEx(started_at_node_id?: [number] | null, started_at_attribute_id?: [number] | null, ended_at_node_id?: [number] | null, ended_at_attribute_id?: [number] | null, created_from_snap?: [boolean] | null): boolean;
    IsLinkDestroyed(link_id: [number]): boolean;
    SaveCurrentEditorStateToIniString(): string;
    SaveEditorStateToIniString(editor: ImNodesEditorContext): string;
    LoadCurrentEditorStateFromIniString(data: string): void;
    LoadEditorStateFromIniString(editor: ImNodesEditorContext, data: string): void;
};
