import { ValueStruct } from './core.js';
import { ImVec2, ImVec4 } from './imgui.js';
export type ImAxis = number;
export type ImPlotAxisFlags = number;
export type ImPlotBarGroupsFlags = number;
export type ImPlotBarsFlags = number;
export type ImPlotBin = number;
export type ImPlotBubblesFlags = number;
export type ImPlotCol = number;
export type ImPlotColormap = number;
export type ImPlotColormapScaleFlags = number;
export type ImPlotCond = number;
export type ImPlotContext = number;
export type ImPlotDateFmt = number;
export type ImPlotDigitalFlags = number;
export type ImPlotDragToolFlags = number;
export type ImPlotDummyFlags = number;
export type ImPlotErrorBarsFlags = number;
export type ImPlotFlags = number;
export type ImPlotHeatmapFlags = number;
export type ImPlotHistogramFlags = number;
export type ImPlotImageFlags = number;
export type ImPlotInfLinesFlags = number;
export type ImPlotInputMap = number;
export type ImPlotItemFlags = number;
export type ImPlotLegendFlags = number;
export type ImPlotLineFlags = number;
export type ImPlotLocation = number;
export type ImPlotMarker = number;
export type ImPlotMarkerInternal = number;
export type ImPlotMouseTextFlags = number;
export type ImPlotPieChartFlags = number;
export type ImPlotPolygonFlags = number;
export type ImPlotProp = number;
export type ImPlotScale = number;
export type ImPlotScatterFlags = number;
export type ImPlotShadedFlags = number;
export type ImPlotStairsFlags = number;
export type ImPlotStemsFlags = number;
export type ImPlotStyle = number;
export type ImPlotStyleVar = number;
export type ImPlotSubplotFlags = number;
export type ImPlotTextFlags = number;
export type ImPlotTimeFmt = number;
export type ImPlotTimeUnit = number;
export declare class ImPlotDateTimeSpec extends ValueStruct {
    Date: number;
    Time: number;
    UseISO8601: boolean;
    Use24HourClock: boolean;
    constructor(Date?: number, Time?: number, UseISO8601?: boolean, Use24HourClock?: boolean);
    static From(obj: ImPlotDateTimeSpec): ImPlotDateTimeSpec;
}
export declare class ImPlotPoint extends ValueStruct {
    x: number;
    y: number;
    constructor(x?: number, y?: number);
    static From(obj: ImPlotPoint): ImPlotPoint;
}
export declare class ImPlotRange extends ValueStruct {
    Min: number;
    Max: number;
    constructor(Min?: number, Max?: number);
    static From(obj: ImPlotRange): ImPlotRange;
}
export declare class ImPlotRect extends ValueStruct {
    X: ImPlotRange;
    Y: ImPlotRange;
    constructor(X?: ImPlotRange, Y?: ImPlotRange);
    static From(obj: ImPlotRect): ImPlotRect;
}
export declare class ImPlotTime extends ValueStruct {
    S: number;
    Us: number;
    constructor(S?: number, Us?: number);
    static From(obj: ImPlotTime): ImPlotTime;
}
export interface ImPlotSpec {
    LineColor: ImVec4;
    LineWeight: number;
    FillColor: ImVec4;
    FillAlpha: number;
    Marker: number;
    MarkerSize: number;
    MarkerLineColor: ImVec4;
    MarkerFillColor: ImVec4;
    Size: number;
    Offset: number;
    Stride: number;
    Flags: number;
}
export declare const ImPlot: {
    Auto: number;
    Axis: {
        X1: number;
        X2: number;
        X3: number;
        Y1: number;
        Y2: number;
        Y3: number;
        COUNT: number;
    };
    AxisFlags: {
        None: number;
        NoLabel: number;
        NoGridLines: number;
        NoTickMarks: number;
        NoTickLabels: number;
        NoInitialFit: number;
        NoMenus: number;
        NoSideSwitch: number;
        NoHighlight: number;
        Opposite: number;
        Foreground: number;
        Invert: number;
        AutoFit: number;
        RangeFit: number;
        PanStretch: number;
        LockMin: number;
        LockMax: number;
        Lock: number;
        NoDecorations: number;
        AuxDefault: number;
    };
    BarGroupsFlags: {
        None: number;
        Horizontal: number;
        Stacked: number;
    };
    BarsFlags: {
        None: number;
        Horizontal: number;
    };
    Bin: {
        Sqrt: number;
        Sturges: number;
        Rice: number;
        Scott: number;
    };
    BubblesFlags: {
        None: number;
    };
    Col: {
        FrameBg: number;
        PlotBg: number;
        PlotBorder: number;
        LegendBg: number;
        LegendBorder: number;
        LegendText: number;
        TitleText: number;
        InlayText: number;
        AxisText: number;
        AxisGrid: number;
        AxisTick: number;
        AxisBg: number;
        AxisBgHovered: number;
        AxisBgActive: number;
        Selection: number;
        Crosshairs: number;
        COUNT: number;
    };
    ColormapScaleFlags: {
        None: number;
        NoLabel: number;
        Opposite: number;
        Invert: number;
    };
    Colormap: {
        Deep: number;
        Dark: number;
        Pastel: number;
        Paired: number;
        Viridis: number;
        Plasma: number;
        Hot: number;
        Cool: number;
        Pink: number;
        Jet: number;
        Twilight: number;
        RdBu: number;
        BrBG: number;
        PiYG: number;
        Spectral: number;
        Greys: number;
    };
    Cond: {
        None: number;
        Always: number;
        Once: number;
    };
    DateFmt: {
        None: number;
        DayMo: number;
        DayMoYr: number;
        MoYr: number;
        Mo: number;
        Yr: number;
    };
    DigitalFlags: {
        None: number;
    };
    DragToolFlags: {
        None: number;
        NoCursors: number;
        NoFit: number;
        NoInputs: number;
        Delayed: number;
    };
    DummyFlags: {
        None: number;
    };
    ErrorBarsFlags: {
        None: number;
        Horizontal: number;
    };
    Flags: {
        None: number;
        NoTitle: number;
        NoLegend: number;
        NoMouseText: number;
        NoInputs: number;
        NoMenus: number;
        NoBoxSelect: number;
        NoFrame: number;
        Equal: number;
        Crosshairs: number;
        CanvasOnly: number;
    };
    HeatmapFlags: {
        None: number;
        ColMajor: number;
    };
    HistogramFlags: {
        None: number;
        Horizontal: number;
        Cumulative: number;
        Density: number;
        NoOutliers: number;
        ColMajor: number;
    };
    ImageFlags: {
        None: number;
    };
    InfLinesFlags: {
        None: number;
        Horizontal: number;
    };
    ItemFlags: {
        None: number;
        NoLegend: number;
        NoFit: number;
    };
    LegendFlags: {
        None: number;
        NoButtons: number;
        NoHighlightItem: number;
        NoHighlightAxis: number;
        NoMenus: number;
        Outside: number;
        Horizontal: number;
        Sort: number;
        Reverse: number;
    };
    LineFlags: {
        None: number;
        Segments: number;
        Loop: number;
        SkipNaN: number;
        NoClip: number;
        Shaded: number;
    };
    Location: {
        Center: number;
        North: number;
        South: number;
        West: number;
        East: number;
        NorthWest: number;
        NorthEast: number;
        SouthWest: number;
        SouthEast: number;
    };
    MarkerInternal: {
        Marker_Invalid: number;
    };
    Marker: {
        None: number;
        Auto: number;
        Circle: number;
        Square: number;
        Diamond: number;
        Up: number;
        Down: number;
        Left: number;
        Right: number;
        Cross: number;
        Plus: number;
        Asterisk: number;
        COUNT: number;
    };
    MouseTextFlags: {
        None: number;
        NoAuxAxes: number;
        NoFormat: number;
        ShowAlways: number;
    };
    PieChartFlags: {
        None: number;
        Normalize: number;
        IgnoreHidden: number;
        Exploding: number;
        NoSliceBorder: number;
    };
    PolygonFlags: {
        None: number;
        Concave: number;
    };
    Prop: {
        LineColor: number;
        LineColors: number;
        LineWeight: number;
        FillColor: number;
        FillColors: number;
        FillAlpha: number;
        Marker: number;
        MarkerSize: number;
        MarkerSizes: number;
        MarkerLineColor: number;
        MarkerLineColors: number;
        MarkerFillColor: number;
        MarkerFillColors: number;
        Size: number;
        Offset: number;
        Stride: number;
        Flags: number;
    };
    Scale: {
        Linear: number;
        Time: number;
        Log10: number;
        SymLog: number;
    };
    ScatterFlags: {
        None: number;
        NoClip: number;
    };
    ShadedFlags: {
        None: number;
    };
    StairsFlags: {
        None: number;
        PreStep: number;
        Shaded: number;
    };
    StemsFlags: {
        None: number;
        Horizontal: number;
    };
    StyleVar: {
        PlotDefaultSize: number;
        PlotMinSize: number;
        PlotBorderSize: number;
        MinorAlpha: number;
        MajorTickLen: number;
        MinorTickLen: number;
        MajorTickSize: number;
        MinorTickSize: number;
        MajorGridSize: number;
        MinorGridSize: number;
        PlotPadding: number;
        LabelPadding: number;
        LegendPadding: number;
        LegendInnerPadding: number;
        LegendSpacing: number;
        MousePosPadding: number;
        AnnotationPadding: number;
        FitPadding: number;
        DigitalPadding: number;
        DigitalSpacing: number;
        COUNT: number;
    };
    SubplotFlags: {
        None: number;
        NoTitle: number;
        NoLegend: number;
        NoMenus: number;
        NoResize: number;
        NoAlign: number;
        ShareItems: number;
        LinkRows: number;
        LinkCols: number;
        LinkAllX: number;
        LinkAllY: number;
        ColMajor: number;
    };
    TextFlags: {
        None: number;
        Vertical: number;
    };
    TimeFmt: {
        None: number;
        Us: number;
        SUs: number;
        SMs: number;
        S: number;
        MinSMs: number;
        HrMinSMs: number;
        HrMinS: number;
        HrMin: number;
        Hr: number;
    };
    TimeUnit: {
        Us: number;
        Ms: number;
        S: number;
        Min: number;
        Hr: number;
        Day: number;
        Mo: number;
        Yr: number;
        COUNT: number;
    };
    AddColormap_U32Ptr(name: string, cols: number[], size: number, qual?: boolean): number;
    AddColormap_Vec4Ptr(name: string, cols: ImVec4[], size: number, qual?: boolean): number;
    Annotation_Bool(x: number, y: number, col: ImVec4, pix_offset: ImVec2, clamp: boolean, round?: boolean): void;
    BeginAlignedPlots(group_id: string, vertical?: boolean): boolean;
    BeginDragDropSourceAxis(axis: number, flags?: number): boolean;
    BeginDragDropSourceItem(label_id: string, flags?: number): boolean;
    BeginDragDropSourcePlot(flags?: number): boolean;
    BeginDragDropTargetAxis(axis: number): boolean;
    BeginDragDropTargetLegend(): boolean;
    BeginDragDropTargetPlot(): boolean;
    BeginLegendPopup(label_id: string, mouse_button?: number): boolean;
    BeginPlot(title_id: string, size?: ImVec2, flags?: number): boolean;
    BeginSubplots(title_id: string, rows: number, cols: number, size: ImVec2, flags?: number, row_ratios?: number[] | null, col_ratios?: number[] | null): boolean;
    BustColorCache(plot_title_id?: string): void;
    CancelPlotSelection(): void;
    ColormapButton(label: string, size?: ImVec2, cmap?: number): boolean;
    ColormapIcon(cmap: number): void;
    ColormapScale(label: string, scale_min: number, scale_max: number, size?: ImVec2, format?: string, flags?: number, cmap?: number): void;
    ColormapSlider(label: string, t: number[], out?: ImVec4[] | null, format?: string, cmap?: number): boolean;
    CreateContext(): number;
    DestroyContext(ctx?: number): void;
    EndAlignedPlots(): void;
    EndDragDropSource(): void;
    EndDragDropTarget(): void;
    EndLegendPopup(): void;
    EndPlot(): void;
    EndSubplots(): void;
    GetColormapColor(idx: number, cmap?: number): ImVec4;
    GetColormapCount(): number;
    GetColormapIndex(name: string): number;
    GetColormapSize(cmap?: number): number;
    GetCurrentContext(): number;
    GetInputMap(): number;
    GetLastItemColor(): ImVec4;
    GetPlotLimits(x_axis?: number, y_axis?: number): ImPlotRect;
    GetPlotMousePos(x_axis?: number, y_axis?: number): ImPlotPoint;
    GetPlotPos(): ImVec2;
    GetPlotSelection(x_axis?: number, y_axis?: number): ImPlotRect;
    GetPlotSize(): ImVec2;
    GetStyle(): number;
    HideNextItem(hidden?: boolean, cond?: number): void;
    IsAxisHovered(axis: number): boolean;
    IsLegendEntryHovered(label_id: string): boolean;
    IsPlotHovered(): boolean;
    IsPlotSelected(): boolean;
    IsSubplotsHovered(): boolean;
    ItemIcon_U32(col: number): void;
    ItemIcon_Vec4(col: ImVec4): void;
    MapInputDefault(dst?: number): void;
    MapInputReverse(dst?: number): void;
    NextColormapColor(): ImVec4;
    NextMarker(): number;
    PixelsToPlot_Float(x: number, y: number, x_axis?: number, y_axis?: number): ImPlotPoint;
    PixelsToPlot_Vec2(pix: ImVec2, x_axis?: number, y_axis?: number): ImPlotPoint;
    PlotBarGroups_doublePtr(label_ids: string[] | null, values: number[], item_count: number, group_count: number, group_size?: number, shift?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBarGroups_FloatPtr(label_ids: string[] | null, values: number[], item_count: number, group_count: number, group_size?: number, shift?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBarGroups_S16Ptr(label_ids: string[] | null, values: number[], item_count: number, group_count: number, group_size?: number, shift?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBarGroups_S32Ptr(label_ids: string[] | null, values: number[], item_count: number, group_count: number, group_size?: number, shift?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBarGroups_S64Ptr(label_ids: string[] | null, values: number[], item_count: number, group_count: number, group_size?: number, shift?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBarGroups_S8Ptr(label_ids: string[] | null, values: number[], item_count: number, group_count: number, group_size?: number, shift?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBarGroups_U16Ptr(label_ids: string[] | null, values: number[], item_count: number, group_count: number, group_size?: number, shift?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBarGroups_U32Ptr(label_ids: string[] | null, values: number[], item_count: number, group_count: number, group_size?: number, shift?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBarGroups_U64Ptr(label_ids: string[] | null, values: number[], item_count: number, group_count: number, group_size?: number, shift?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBarGroups_U8Ptr(label_ids: string[] | null, values: number[], item_count: number, group_count: number, group_size?: number, shift?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBars_doublePtrdoublePtr(label_id: string, xs: number[], ys: number[], count: number, bar_size: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBars_doublePtrInt(label_id: string, values: number[], count: number, bar_size?: number, shift?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBars_FloatPtrFloatPtr(label_id: string, xs: number[], ys: number[], count: number, bar_size: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBars_FloatPtrInt(label_id: string, values: number[], count: number, bar_size?: number, shift?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBars_S16PtrInt(label_id: string, values: number[], count: number, bar_size?: number, shift?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBars_S16PtrS16Ptr(label_id: string, xs: number[], ys: number[], count: number, bar_size: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBars_S32PtrInt(label_id: string, values: number[], count: number, bar_size?: number, shift?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBars_S32PtrS32Ptr(label_id: string, xs: number[], ys: number[], count: number, bar_size: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBars_S64PtrInt(label_id: string, values: number[], count: number, bar_size?: number, shift?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBars_S64PtrS64Ptr(label_id: string, xs: number[], ys: number[], count: number, bar_size: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBars_S8PtrInt(label_id: string, values: number[], count: number, bar_size?: number, shift?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBars_S8PtrS8Ptr(label_id: string, xs: number[], ys: number[], count: number, bar_size: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBars_U16PtrInt(label_id: string, values: number[], count: number, bar_size?: number, shift?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBars_U16PtrU16Ptr(label_id: string, xs: number[], ys: number[], count: number, bar_size: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBars_U32PtrInt(label_id: string, values: number[], count: number, bar_size?: number, shift?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBars_U32PtrU32Ptr(label_id: string, xs: number[], ys: number[], count: number, bar_size: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBars_U64PtrInt(label_id: string, values: number[], count: number, bar_size?: number, shift?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBars_U64PtrU64Ptr(label_id: string, xs: number[], ys: number[], count: number, bar_size: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBars_U8PtrInt(label_id: string, values: number[], count: number, bar_size?: number, shift?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBars_U8PtrU8Ptr(label_id: string, xs: number[], ys: number[], count: number, bar_size: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBubbles_doublePtrdoublePtrdoublePtr(label_id: string, xs: number[], ys: number[], szs: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBubbles_doublePtrdoublePtrInt(label_id: string, values: number[], szs: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBubbles_FloatPtrFloatPtrFloatPtr(label_id: string, xs: number[], ys: number[], szs: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBubbles_FloatPtrFloatPtrInt(label_id: string, values: number[], szs: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBubbles_S16PtrS16PtrInt(label_id: string, values: number[], szs: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBubbles_S16PtrS16PtrS16Ptr(label_id: string, xs: number[], ys: number[], szs: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBubbles_S32PtrS32PtrInt(label_id: string, values: number[], szs: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBubbles_S32PtrS32PtrS32Ptr(label_id: string, xs: number[], ys: number[], szs: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBubbles_S64PtrS64PtrInt(label_id: string, values: number[], szs: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBubbles_S64PtrS64PtrS64Ptr(label_id: string, xs: number[], ys: number[], szs: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBubbles_S8PtrS8PtrInt(label_id: string, values: number[], szs: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBubbles_S8PtrS8PtrS8Ptr(label_id: string, xs: number[], ys: number[], szs: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBubbles_U16PtrU16PtrInt(label_id: string, values: number[], szs: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBubbles_U16PtrU16PtrU16Ptr(label_id: string, xs: number[], ys: number[], szs: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBubbles_U32PtrU32PtrInt(label_id: string, values: number[], szs: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBubbles_U32PtrU32PtrU32Ptr(label_id: string, xs: number[], ys: number[], szs: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBubbles_U64PtrU64PtrInt(label_id: string, values: number[], szs: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBubbles_U64PtrU64PtrU64Ptr(label_id: string, xs: number[], ys: number[], szs: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBubbles_U8PtrU8PtrInt(label_id: string, values: number[], szs: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotBubbles_U8PtrU8PtrU8Ptr(label_id: string, xs: number[], ys: number[], szs: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotDigital_doublePtr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotDigital_FloatPtr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotDigital_S16Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotDigital_S32Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotDigital_S64Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotDigital_S8Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotDigital_U16Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotDigital_U32Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotDigital_U64Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotDigital_U8Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotDummy(label_id: string, spec?: Partial<ImPlotSpec> | null): void;
    PlotErrorBars_doublePtrdoublePtrdoublePtrdoublePtr(label_id: string, xs: number[], ys: number[], neg: number[], pos: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotErrorBars_doublePtrdoublePtrdoublePtrInt(label_id: string, xs: number[], ys: number[], err: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotErrorBars_FloatPtrFloatPtrFloatPtrFloatPtr(label_id: string, xs: number[], ys: number[], neg: number[], pos: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotErrorBars_FloatPtrFloatPtrFloatPtrInt(label_id: string, xs: number[], ys: number[], err: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotErrorBars_S16PtrS16PtrS16PtrInt(label_id: string, xs: number[], ys: number[], err: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotErrorBars_S16PtrS16PtrS16PtrS16Ptr(label_id: string, xs: number[], ys: number[], neg: number[], pos: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotErrorBars_S32PtrS32PtrS32PtrInt(label_id: string, xs: number[], ys: number[], err: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotErrorBars_S32PtrS32PtrS32PtrS32Ptr(label_id: string, xs: number[], ys: number[], neg: number[], pos: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotErrorBars_S64PtrS64PtrS64PtrInt(label_id: string, xs: number[], ys: number[], err: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotErrorBars_S64PtrS64PtrS64PtrS64Ptr(label_id: string, xs: number[], ys: number[], neg: number[], pos: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotErrorBars_S8PtrS8PtrS8PtrInt(label_id: string, xs: number[], ys: number[], err: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotErrorBars_S8PtrS8PtrS8PtrS8Ptr(label_id: string, xs: number[], ys: number[], neg: number[], pos: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotErrorBars_U16PtrU16PtrU16PtrInt(label_id: string, xs: number[], ys: number[], err: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotErrorBars_U16PtrU16PtrU16PtrU16Ptr(label_id: string, xs: number[], ys: number[], neg: number[], pos: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotErrorBars_U32PtrU32PtrU32PtrInt(label_id: string, xs: number[], ys: number[], err: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotErrorBars_U32PtrU32PtrU32PtrU32Ptr(label_id: string, xs: number[], ys: number[], neg: number[], pos: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotErrorBars_U64PtrU64PtrU64PtrInt(label_id: string, xs: number[], ys: number[], err: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotErrorBars_U64PtrU64PtrU64PtrU64Ptr(label_id: string, xs: number[], ys: number[], neg: number[], pos: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotErrorBars_U8PtrU8PtrU8PtrInt(label_id: string, xs: number[], ys: number[], err: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotErrorBars_U8PtrU8PtrU8PtrU8Ptr(label_id: string, xs: number[], ys: number[], neg: number[], pos: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotHeatmap_doublePtr(label_id: string, values: number[], rows: number, cols: number, scale_min?: number, scale_max?: number, label_fmt?: string, bounds_min?: ImPlotPoint, bounds_max?: ImPlotPoint, spec?: Partial<ImPlotSpec> | null): void;
    PlotHeatmap_FloatPtr(label_id: string, values: number[], rows: number, cols: number, scale_min?: number, scale_max?: number, label_fmt?: string, bounds_min?: ImPlotPoint, bounds_max?: ImPlotPoint, spec?: Partial<ImPlotSpec> | null): void;
    PlotHeatmap_S16Ptr(label_id: string, values: number[], rows: number, cols: number, scale_min?: number, scale_max?: number, label_fmt?: string, bounds_min?: ImPlotPoint, bounds_max?: ImPlotPoint, spec?: Partial<ImPlotSpec> | null): void;
    PlotHeatmap_S32Ptr(label_id: string, values: number[], rows: number, cols: number, scale_min?: number, scale_max?: number, label_fmt?: string, bounds_min?: ImPlotPoint, bounds_max?: ImPlotPoint, spec?: Partial<ImPlotSpec> | null): void;
    PlotHeatmap_S64Ptr(label_id: string, values: number[], rows: number, cols: number, scale_min?: number, scale_max?: number, label_fmt?: string, bounds_min?: ImPlotPoint, bounds_max?: ImPlotPoint, spec?: Partial<ImPlotSpec> | null): void;
    PlotHeatmap_S8Ptr(label_id: string, values: number[], rows: number, cols: number, scale_min?: number, scale_max?: number, label_fmt?: string, bounds_min?: ImPlotPoint, bounds_max?: ImPlotPoint, spec?: Partial<ImPlotSpec> | null): void;
    PlotHeatmap_U16Ptr(label_id: string, values: number[], rows: number, cols: number, scale_min?: number, scale_max?: number, label_fmt?: string, bounds_min?: ImPlotPoint, bounds_max?: ImPlotPoint, spec?: Partial<ImPlotSpec> | null): void;
    PlotHeatmap_U32Ptr(label_id: string, values: number[], rows: number, cols: number, scale_min?: number, scale_max?: number, label_fmt?: string, bounds_min?: ImPlotPoint, bounds_max?: ImPlotPoint, spec?: Partial<ImPlotSpec> | null): void;
    PlotHeatmap_U64Ptr(label_id: string, values: number[], rows: number, cols: number, scale_min?: number, scale_max?: number, label_fmt?: string, bounds_min?: ImPlotPoint, bounds_max?: ImPlotPoint, spec?: Partial<ImPlotSpec> | null): void;
    PlotHeatmap_U8Ptr(label_id: string, values: number[], rows: number, cols: number, scale_min?: number, scale_max?: number, label_fmt?: string, bounds_min?: ImPlotPoint, bounds_max?: ImPlotPoint, spec?: Partial<ImPlotSpec> | null): void;
    PlotHistogram_doublePtr(label_id: string, values: number[], count: number, bins?: number, bar_scale?: number, range?: ImPlotRange, spec?: Partial<ImPlotSpec> | null): number;
    PlotHistogram_FloatPtr(label_id: string, values: number[], count: number, bins?: number, bar_scale?: number, range?: ImPlotRange, spec?: Partial<ImPlotSpec> | null): number;
    PlotHistogram_S16Ptr(label_id: string, values: number[], count: number, bins?: number, bar_scale?: number, range?: ImPlotRange, spec?: Partial<ImPlotSpec> | null): number;
    PlotHistogram_S32Ptr(label_id: string, values: number[], count: number, bins?: number, bar_scale?: number, range?: ImPlotRange, spec?: Partial<ImPlotSpec> | null): number;
    PlotHistogram_S64Ptr(label_id: string, values: number[], count: number, bins?: number, bar_scale?: number, range?: ImPlotRange, spec?: Partial<ImPlotSpec> | null): number;
    PlotHistogram_S8Ptr(label_id: string, values: number[], count: number, bins?: number, bar_scale?: number, range?: ImPlotRange, spec?: Partial<ImPlotSpec> | null): number;
    PlotHistogram_U16Ptr(label_id: string, values: number[], count: number, bins?: number, bar_scale?: number, range?: ImPlotRange, spec?: Partial<ImPlotSpec> | null): number;
    PlotHistogram_U32Ptr(label_id: string, values: number[], count: number, bins?: number, bar_scale?: number, range?: ImPlotRange, spec?: Partial<ImPlotSpec> | null): number;
    PlotHistogram_U64Ptr(label_id: string, values: number[], count: number, bins?: number, bar_scale?: number, range?: ImPlotRange, spec?: Partial<ImPlotSpec> | null): number;
    PlotHistogram_U8Ptr(label_id: string, values: number[], count: number, bins?: number, bar_scale?: number, range?: ImPlotRange, spec?: Partial<ImPlotSpec> | null): number;
    PlotHistogram2D_doublePtr(label_id: string, xs: number[], ys: number[], count: number, x_bins?: number, y_bins?: number, range?: ImPlotRect, spec?: Partial<ImPlotSpec> | null): number;
    PlotHistogram2D_FloatPtr(label_id: string, xs: number[], ys: number[], count: number, x_bins?: number, y_bins?: number, range?: ImPlotRect, spec?: Partial<ImPlotSpec> | null): number;
    PlotHistogram2D_S16Ptr(label_id: string, xs: number[], ys: number[], count: number, x_bins?: number, y_bins?: number, range?: ImPlotRect, spec?: Partial<ImPlotSpec> | null): number;
    PlotHistogram2D_S32Ptr(label_id: string, xs: number[], ys: number[], count: number, x_bins?: number, y_bins?: number, range?: ImPlotRect, spec?: Partial<ImPlotSpec> | null): number;
    PlotHistogram2D_S64Ptr(label_id: string, xs: number[], ys: number[], count: number, x_bins?: number, y_bins?: number, range?: ImPlotRect, spec?: Partial<ImPlotSpec> | null): number;
    PlotHistogram2D_S8Ptr(label_id: string, xs: number[], ys: number[], count: number, x_bins?: number, y_bins?: number, range?: ImPlotRect, spec?: Partial<ImPlotSpec> | null): number;
    PlotHistogram2D_U16Ptr(label_id: string, xs: number[], ys: number[], count: number, x_bins?: number, y_bins?: number, range?: ImPlotRect, spec?: Partial<ImPlotSpec> | null): number;
    PlotHistogram2D_U32Ptr(label_id: string, xs: number[], ys: number[], count: number, x_bins?: number, y_bins?: number, range?: ImPlotRect, spec?: Partial<ImPlotSpec> | null): number;
    PlotHistogram2D_U64Ptr(label_id: string, xs: number[], ys: number[], count: number, x_bins?: number, y_bins?: number, range?: ImPlotRect, spec?: Partial<ImPlotSpec> | null): number;
    PlotHistogram2D_U8Ptr(label_id: string, xs: number[], ys: number[], count: number, x_bins?: number, y_bins?: number, range?: ImPlotRect, spec?: Partial<ImPlotSpec> | null): number;
    PlotInfLines_doublePtr(label_id: string, values: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotInfLines_FloatPtr(label_id: string, values: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotInfLines_S16Ptr(label_id: string, values: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotInfLines_S32Ptr(label_id: string, values: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotInfLines_S64Ptr(label_id: string, values: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotInfLines_S8Ptr(label_id: string, values: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotInfLines_U16Ptr(label_id: string, values: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotInfLines_U32Ptr(label_id: string, values: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotInfLines_U64Ptr(label_id: string, values: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotInfLines_U8Ptr(label_id: string, values: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotLine_doublePtrdoublePtr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotLine_doublePtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotLine_FloatPtrFloatPtr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotLine_FloatPtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotLine_S16PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotLine_S16PtrS16Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotLine_S32PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotLine_S32PtrS32Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotLine_S64PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotLine_S64PtrS64Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotLine_S8PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotLine_S8PtrS8Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotLine_U16PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotLine_U16PtrU16Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotLine_U32PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotLine_U32PtrU32Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotLine_U64PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotLine_U64PtrU64Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotLine_U8PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotLine_U8PtrU8Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotPieChart_doublePtrStr(label_ids: string[] | null, values: number[], count: number, x: number, y: number, radius: number, label_fmt?: string, angle0?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotPieChart_FloatPtrStr(label_ids: string[] | null, values: number[], count: number, x: number, y: number, radius: number, label_fmt?: string, angle0?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotPieChart_S16PtrStr(label_ids: string[] | null, values: number[], count: number, x: number, y: number, radius: number, label_fmt?: string, angle0?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotPieChart_S32PtrStr(label_ids: string[] | null, values: number[], count: number, x: number, y: number, radius: number, label_fmt?: string, angle0?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotPieChart_S64PtrStr(label_ids: string[] | null, values: number[], count: number, x: number, y: number, radius: number, label_fmt?: string, angle0?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotPieChart_S8PtrStr(label_ids: string[] | null, values: number[], count: number, x: number, y: number, radius: number, label_fmt?: string, angle0?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotPieChart_U16PtrStr(label_ids: string[] | null, values: number[], count: number, x: number, y: number, radius: number, label_fmt?: string, angle0?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotPieChart_U32PtrStr(label_ids: string[] | null, values: number[], count: number, x: number, y: number, radius: number, label_fmt?: string, angle0?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotPieChart_U64PtrStr(label_ids: string[] | null, values: number[], count: number, x: number, y: number, radius: number, label_fmt?: string, angle0?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotPieChart_U8PtrStr(label_ids: string[] | null, values: number[], count: number, x: number, y: number, radius: number, label_fmt?: string, angle0?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotPolygon_doublePtr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotPolygon_FloatPtr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotPolygon_S16Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotPolygon_S32Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotPolygon_S64Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotPolygon_S8Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotPolygon_U16Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotPolygon_U32Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotPolygon_U64Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotPolygon_U8Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotScatter_doublePtrdoublePtr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotScatter_doublePtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotScatter_FloatPtrFloatPtr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotScatter_FloatPtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotScatter_S16PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotScatter_S16PtrS16Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotScatter_S32PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotScatter_S32PtrS32Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotScatter_S64PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotScatter_S64PtrS64Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotScatter_S8PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotScatter_S8PtrS8Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotScatter_U16PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotScatter_U16PtrU16Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotScatter_U32PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotScatter_U32PtrU32Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotScatter_U64PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotScatter_U64PtrU64Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotScatter_U8PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotScatter_U8PtrU8Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_doublePtrdoublePtrdoublePtr(label_id: string, xs: number[], ys1: number[], ys2: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_doublePtrdoublePtrInt(label_id: string, xs: number[], ys: number[], count: number, yref?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_doublePtrInt(label_id: string, values: number[], count: number, yref?: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_FloatPtrFloatPtrFloatPtr(label_id: string, xs: number[], ys1: number[], ys2: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_FloatPtrFloatPtrInt(label_id: string, xs: number[], ys: number[], count: number, yref?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_FloatPtrInt(label_id: string, values: number[], count: number, yref?: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_S16PtrInt(label_id: string, values: number[], count: number, yref?: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_S16PtrS16PtrInt(label_id: string, xs: number[], ys: number[], count: number, yref?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_S16PtrS16PtrS16Ptr(label_id: string, xs: number[], ys1: number[], ys2: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_S32PtrInt(label_id: string, values: number[], count: number, yref?: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_S32PtrS32PtrInt(label_id: string, xs: number[], ys: number[], count: number, yref?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_S32PtrS32PtrS32Ptr(label_id: string, xs: number[], ys1: number[], ys2: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_S64PtrInt(label_id: string, values: number[], count: number, yref?: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_S64PtrS64PtrInt(label_id: string, xs: number[], ys: number[], count: number, yref?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_S64PtrS64PtrS64Ptr(label_id: string, xs: number[], ys1: number[], ys2: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_S8PtrInt(label_id: string, values: number[], count: number, yref?: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_S8PtrS8PtrInt(label_id: string, xs: number[], ys: number[], count: number, yref?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_S8PtrS8PtrS8Ptr(label_id: string, xs: number[], ys1: number[], ys2: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_U16PtrInt(label_id: string, values: number[], count: number, yref?: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_U16PtrU16PtrInt(label_id: string, xs: number[], ys: number[], count: number, yref?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_U16PtrU16PtrU16Ptr(label_id: string, xs: number[], ys1: number[], ys2: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_U32PtrInt(label_id: string, values: number[], count: number, yref?: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_U32PtrU32PtrInt(label_id: string, xs: number[], ys: number[], count: number, yref?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_U32PtrU32PtrU32Ptr(label_id: string, xs: number[], ys1: number[], ys2: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_U64PtrInt(label_id: string, values: number[], count: number, yref?: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_U64PtrU64PtrInt(label_id: string, xs: number[], ys: number[], count: number, yref?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_U64PtrU64PtrU64Ptr(label_id: string, xs: number[], ys1: number[], ys2: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_U8PtrInt(label_id: string, values: number[], count: number, yref?: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_U8PtrU8PtrInt(label_id: string, xs: number[], ys: number[], count: number, yref?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotShaded_U8PtrU8PtrU8Ptr(label_id: string, xs: number[], ys1: number[], ys2: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStairs_doublePtrdoublePtr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStairs_doublePtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStairs_FloatPtrFloatPtr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStairs_FloatPtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStairs_S16PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStairs_S16PtrS16Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStairs_S32PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStairs_S32PtrS32Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStairs_S64PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStairs_S64PtrS64Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStairs_S8PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStairs_S8PtrS8Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStairs_U16PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStairs_U16PtrU16Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStairs_U32PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStairs_U32PtrU32Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStairs_U64PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStairs_U64PtrU64Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStairs_U8PtrInt(label_id: string, values: number[], count: number, xscale?: number, xstart?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStairs_U8PtrU8Ptr(label_id: string, xs: number[], ys: number[], count: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStems_doublePtrdoublePtr(label_id: string, xs: number[], ys: number[], count: number, ref?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStems_doublePtrInt(label_id: string, values: number[], count: number, ref?: number, scale?: number, start?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStems_FloatPtrFloatPtr(label_id: string, xs: number[], ys: number[], count: number, ref?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStems_FloatPtrInt(label_id: string, values: number[], count: number, ref?: number, scale?: number, start?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStems_S16PtrInt(label_id: string, values: number[], count: number, ref?: number, scale?: number, start?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStems_S16PtrS16Ptr(label_id: string, xs: number[], ys: number[], count: number, ref?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStems_S32PtrInt(label_id: string, values: number[], count: number, ref?: number, scale?: number, start?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStems_S32PtrS32Ptr(label_id: string, xs: number[], ys: number[], count: number, ref?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStems_S64PtrInt(label_id: string, values: number[], count: number, ref?: number, scale?: number, start?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStems_S64PtrS64Ptr(label_id: string, xs: number[], ys: number[], count: number, ref?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStems_S8PtrInt(label_id: string, values: number[], count: number, ref?: number, scale?: number, start?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStems_S8PtrS8Ptr(label_id: string, xs: number[], ys: number[], count: number, ref?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStems_U16PtrInt(label_id: string, values: number[], count: number, ref?: number, scale?: number, start?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStems_U16PtrU16Ptr(label_id: string, xs: number[], ys: number[], count: number, ref?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStems_U32PtrInt(label_id: string, values: number[], count: number, ref?: number, scale?: number, start?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStems_U32PtrU32Ptr(label_id: string, xs: number[], ys: number[], count: number, ref?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStems_U64PtrInt(label_id: string, values: number[], count: number, ref?: number, scale?: number, start?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStems_U64PtrU64Ptr(label_id: string, xs: number[], ys: number[], count: number, ref?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStems_U8PtrInt(label_id: string, values: number[], count: number, ref?: number, scale?: number, start?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotStems_U8PtrU8Ptr(label_id: string, xs: number[], ys: number[], count: number, ref?: number, spec?: Partial<ImPlotSpec> | null): void;
    PlotText(text: string, x: number, y: number, pix_offset?: ImVec2, spec?: Partial<ImPlotSpec> | null): void;
    PlotToPixels_double(x: number, y: number, x_axis?: number, y_axis?: number): ImVec2;
    PlotToPixels_PlotPoint(plt: ImPlotPoint, x_axis?: number, y_axis?: number): ImVec2;
    PopColormap(count?: number): void;
    PopPlotClipRect(): void;
    PopStyleColor(count?: number): void;
    PopStyleVar(count?: number): void;
    PushColormap_PlotColormap(cmap: number): void;
    PushColormap_Str(name: string): void;
    PushPlotClipRect(expand?: number): void;
    PushStyleColor_U32(idx: number, col: number): void;
    PushStyleColor_Vec4(idx: number, col: ImVec4): void;
    PushStyleVar_Float(idx: number, val: number): void;
    PushStyleVar_Int(idx: number, val: number): void;
    PushStyleVar_Vec2(idx: number, val: ImVec2): void;
    SampleColormap(t: number, cmap?: number): ImVec4;
    SetAxes(x_axis: number, y_axis: number): void;
    SetAxis(axis: number): void;
    SetCurrentContext(ctx: number): void;
    SetImGuiContext(ctx: number): void;
    SetNextAxesLimits(x_min: number, x_max: number, y_min: number, y_max: number, cond?: number): void;
    SetNextAxesToFit(): void;
    SetNextAxisLimits(axis: number, v_min: number, v_max: number, cond?: number): void;
    SetNextAxisLinks(axis: number, link_min: number[], link_max: number[]): void;
    SetNextAxisToFit(axis: number): void;
    SetupAxes(x_label: string, y_label: string, x_flags?: number, y_flags?: number): void;
    SetupAxesLimits(x_min: number, x_max: number, y_min: number, y_max: number, cond?: number): void;
    SetupAxis(axis: number, label?: string, flags?: number): void;
    SetupAxisFormat_Str(axis: number, fmt: string): void;
    SetupAxisLimits(axis: number, v_min: number, v_max: number, cond?: number): void;
    SetupAxisLimitsConstraints(axis: number, v_min: number, v_max: number): void;
    SetupAxisLinks(axis: number, link_min: number[], link_max: number[]): void;
    SetupAxisScale_PlotScale(axis: number, scale: number): void;
    SetupAxisTicks_double(axis: number, v_min: number, v_max: number, n_ticks: number, labels?: string[] | null, keep_default?: boolean): void;
    SetupAxisTicks_doublePtr(axis: number, values: number[], n_ticks: number, labels?: string[] | null, keep_default?: boolean): void;
    SetupAxisZoomConstraints(axis: number, z_min: number, z_max: number): void;
    SetupFinish(): void;
    SetupLegend(location: number, flags?: number): void;
    SetupMouseText(location: number, flags?: number): void;
    ShowColormapSelector(label: string): boolean;
    ShowInputMapSelector(label: string): boolean;
    ShowStyleEditor(ref?: number): void;
    ShowStyleSelector(label: string): boolean;
    ShowUserGuide(): void;
    StyleColorsAuto(dst?: number): void;
    StyleColorsClassic(dst?: number): void;
    StyleColorsDark(dst?: number): void;
    StyleColorsLight(dst?: number): void;
    TagX_Bool(x: number, col: ImVec4, round?: boolean): void;
    TagY_Bool(y: number, col: ImVec4, round?: boolean): void;
    InputMap_destroy(self: number): void;
    InputMap_ImPlotInputMap(): number;
    Point_destroy(self: number): void;
    Point_ImPlotPoint_double(_x: number, _y: number): number;
    Point_ImPlotPoint_Nil(): number;
    Point_ImPlotPoint_Vec2(p: ImVec2): number;
    Range_Clamp(self: number, value: number): number;
    Range_Contains(self: number, value: number): boolean;
    Range_destroy(self: number): void;
    Range_ImPlotRange_double(_min: number, _max: number): number;
    Range_ImPlotRange_Nil(): number;
    Range_Size(self: number): number;
    Rect_Clamp_double(self: number, x: number, y: number): ImPlotPoint;
    Rect_Clamp_PlotPoint(self: number, p: ImPlotPoint): ImPlotPoint;
    Rect_Contains_double(self: number, x: number, y: number): boolean;
    Rect_Contains_PlotPoint(self: number, p: ImPlotPoint): boolean;
    Rect_destroy(self: number): void;
    Rect_ImPlotRect_double(x_min: number, x_max: number, y_min: number, y_max: number): number;
    Rect_ImPlotRect_Nil(): number;
    Rect_Max(self: number): ImPlotPoint;
    Rect_Min(self: number): ImPlotPoint;
    Rect_Size(self: number): ImPlotPoint;
    Spec_destroy(self: number): void;
    Spec_ImPlotSpec(): number;
    Spec_SetProp_double(self: number, prop: number, v: number): void;
    Spec_SetProp_Float(self: number, prop: number, v: number): void;
    Spec_SetProp_FloatPtr(self: number, prop: number, v: number[]): void;
    Spec_SetProp_S16(self: number, prop: number, v: number): void;
    Spec_SetProp_S32(self: number, prop: number, v: number): void;
    Spec_SetProp_S64(self: number, prop: number, v: number): void;
    Spec_SetProp_S8(self: number, prop: number, v: number): void;
    Spec_SetProp_U16(self: number, prop: number, v: number): void;
    Spec_SetProp_U32(self: number, prop: number, v: number): void;
    Spec_SetProp_U32Ptr(self: number, prop: number, v: number[]): void;
    Spec_SetProp_U64(self: number, prop: number, v: number): void;
    Spec_SetProp_U8(self: number, prop: number, v: number): void;
    Spec_SetProp_Vec4(self: number, prop: number, v: ImVec4): void;
    Style_destroy(self: number): void;
    Style_ImPlotStyle(): number;
};
