package imguijs;

#if js
/**
	Generated by `tools/generate-jsimgui-externs.mjs` from
	`lib/jsimgui/build/mod.d.ts`.
**/

@:keep @:native("globalThis.__imguiHxJsImGui.ImGuiImplWeb") extern class ImGuiImplWeb {
	@:native("GetEmscriptenExports")
	static function getEmscriptenExports():Dynamic;
	@:native("GetMemoryInfo")
	static function getMemoryInfo():Dynamic;
	@:native("SetSaveIniSettingsFn")
	static function setSaveIniSettingsFn(fn:Dynamic):Void;
	@:native("SetLoadIniSettingsFn")
	static function setLoadIniSettingsFn(fn:Dynamic):Void;
	@:native("LoadTexture")
	static function loadTexture(?data:Dynamic, ?options:Dynamic):ImGui.ImTextureRef;
	@:native("LoadFont")
	static function loadFont(filename:String, fontData:js.lib.Uint8Array):Void;
	@:native("BeginRender")
	static function beginRender():Void;
	@:native("EndRender")
	static function endRender(?passEncoder:Dynamic):Void;
	@:native("Init")
	static function init(options:Dynamic):js.lib.Promise<Void>;
}
#end
