package imguijs;

#if js
import js.Syntax;
import imguijs.Abstracts;

/**
	Generated by `tools/generate-jsimgui-externs.mjs` from
	`runtime/jsimgui/*.d.ts`.
**/

typedef ImPlotContext = Float;

typedef ImPlotInputMap = Float;

typedef ImPlotStyle = Float;

abstract ImAxis(Int) from Int to Int {
	public static var X1(get, never):ImAxis;

	static inline function get_X1():ImAxis {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Axis.X1");
	}

	public static var X2(get, never):ImAxis;

	static inline function get_X2():ImAxis {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Axis.X2");
	}

	public static var X3(get, never):ImAxis;

	static inline function get_X3():ImAxis {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Axis.X3");
	}

	public static var Y1(get, never):ImAxis;

	static inline function get_Y1():ImAxis {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Axis.Y1");
	}

	public static var Y2(get, never):ImAxis;

	static inline function get_Y2():ImAxis {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Axis.Y2");
	}

	public static var Y3(get, never):ImAxis;

	static inline function get_Y3():ImAxis {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Axis.Y3");
	}

	public static var COUNT(get, never):ImAxis;

	static inline function get_COUNT():ImAxis {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Axis.COUNT");
	}
}

abstract ImPlotAxisFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotAxisFlags;

	static inline function get_None():ImPlotAxisFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.AxisFlags.None");
	}

	public static var NoLabel(get, never):ImPlotAxisFlags;

	static inline function get_NoLabel():ImPlotAxisFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.AxisFlags.NoLabel");
	}

	public static var NoGridLines(get, never):ImPlotAxisFlags;

	static inline function get_NoGridLines():ImPlotAxisFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.AxisFlags.NoGridLines");
	}

	public static var NoTickMarks(get, never):ImPlotAxisFlags;

	static inline function get_NoTickMarks():ImPlotAxisFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.AxisFlags.NoTickMarks");
	}

	public static var NoTickLabels(get, never):ImPlotAxisFlags;

	static inline function get_NoTickLabels():ImPlotAxisFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.AxisFlags.NoTickLabels");
	}

	public static var NoInitialFit(get, never):ImPlotAxisFlags;

	static inline function get_NoInitialFit():ImPlotAxisFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.AxisFlags.NoInitialFit");
	}

	public static var NoMenus(get, never):ImPlotAxisFlags;

	static inline function get_NoMenus():ImPlotAxisFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.AxisFlags.NoMenus");
	}

	public static var NoSideSwitch(get, never):ImPlotAxisFlags;

	static inline function get_NoSideSwitch():ImPlotAxisFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.AxisFlags.NoSideSwitch");
	}

	public static var NoHighlight(get, never):ImPlotAxisFlags;

	static inline function get_NoHighlight():ImPlotAxisFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.AxisFlags.NoHighlight");
	}

	public static var Opposite(get, never):ImPlotAxisFlags;

	static inline function get_Opposite():ImPlotAxisFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.AxisFlags.Opposite");
	}

	public static var Foreground(get, never):ImPlotAxisFlags;

	static inline function get_Foreground():ImPlotAxisFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.AxisFlags.Foreground");
	}

	public static var Invert(get, never):ImPlotAxisFlags;

	static inline function get_Invert():ImPlotAxisFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.AxisFlags.Invert");
	}

	public static var AutoFit(get, never):ImPlotAxisFlags;

	static inline function get_AutoFit():ImPlotAxisFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.AxisFlags.AutoFit");
	}

	public static var RangeFit(get, never):ImPlotAxisFlags;

	static inline function get_RangeFit():ImPlotAxisFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.AxisFlags.RangeFit");
	}

	public static var PanStretch(get, never):ImPlotAxisFlags;

	static inline function get_PanStretch():ImPlotAxisFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.AxisFlags.PanStretch");
	}

	public static var LockMin(get, never):ImPlotAxisFlags;

	static inline function get_LockMin():ImPlotAxisFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.AxisFlags.LockMin");
	}

	public static var LockMax(get, never):ImPlotAxisFlags;

	static inline function get_LockMax():ImPlotAxisFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.AxisFlags.LockMax");
	}

	public static var Lock(get, never):ImPlotAxisFlags;

	static inline function get_Lock():ImPlotAxisFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.AxisFlags.Lock");
	}

	public static var NoDecorations(get, never):ImPlotAxisFlags;

	static inline function get_NoDecorations():ImPlotAxisFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.AxisFlags.NoDecorations");
	}

	public static var AuxDefault(get, never):ImPlotAxisFlags;

	static inline function get_AuxDefault():ImPlotAxisFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.AxisFlags.AuxDefault");
	}
}

abstract ImPlotBarGroupsFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotBarGroupsFlags;

	static inline function get_None():ImPlotBarGroupsFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.BarGroupsFlags.None");
	}

	public static var Horizontal(get, never):ImPlotBarGroupsFlags;

	static inline function get_Horizontal():ImPlotBarGroupsFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.BarGroupsFlags.Horizontal");
	}

	public static var Stacked(get, never):ImPlotBarGroupsFlags;

	static inline function get_Stacked():ImPlotBarGroupsFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.BarGroupsFlags.Stacked");
	}
}

abstract ImPlotBarsFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotBarsFlags;

	static inline function get_None():ImPlotBarsFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.BarsFlags.None");
	}

	public static var Horizontal(get, never):ImPlotBarsFlags;

	static inline function get_Horizontal():ImPlotBarsFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.BarsFlags.Horizontal");
	}
}

abstract ImPlotBin(Int) from Int to Int {
	public static var Sqrt(get, never):ImPlotBin;

	static inline function get_Sqrt():ImPlotBin {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Bin.Sqrt");
	}

	public static var Sturges(get, never):ImPlotBin;

	static inline function get_Sturges():ImPlotBin {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Bin.Sturges");
	}

	public static var Rice(get, never):ImPlotBin;

	static inline function get_Rice():ImPlotBin {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Bin.Rice");
	}

	public static var Scott(get, never):ImPlotBin;

	static inline function get_Scott():ImPlotBin {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Bin.Scott");
	}
}

abstract ImPlotBubblesFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotBubblesFlags;

	static inline function get_None():ImPlotBubblesFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.BubblesFlags.None");
	}
}

abstract ImPlotCol(Int) from Int to Int {
	public static var FrameBg(get, never):ImPlotCol;

	static inline function get_FrameBg():ImPlotCol {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Col.FrameBg");
	}

	public static var PlotBg(get, never):ImPlotCol;

	static inline function get_PlotBg():ImPlotCol {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Col.PlotBg");
	}

	public static var PlotBorder(get, never):ImPlotCol;

	static inline function get_PlotBorder():ImPlotCol {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Col.PlotBorder");
	}

	public static var LegendBg(get, never):ImPlotCol;

	static inline function get_LegendBg():ImPlotCol {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Col.LegendBg");
	}

	public static var LegendBorder(get, never):ImPlotCol;

	static inline function get_LegendBorder():ImPlotCol {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Col.LegendBorder");
	}

	public static var LegendText(get, never):ImPlotCol;

	static inline function get_LegendText():ImPlotCol {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Col.LegendText");
	}

	public static var TitleText(get, never):ImPlotCol;

	static inline function get_TitleText():ImPlotCol {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Col.TitleText");
	}

	public static var InlayText(get, never):ImPlotCol;

	static inline function get_InlayText():ImPlotCol {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Col.InlayText");
	}

	public static var AxisText(get, never):ImPlotCol;

	static inline function get_AxisText():ImPlotCol {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Col.AxisText");
	}

	public static var AxisGrid(get, never):ImPlotCol;

	static inline function get_AxisGrid():ImPlotCol {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Col.AxisGrid");
	}

	public static var AxisTick(get, never):ImPlotCol;

	static inline function get_AxisTick():ImPlotCol {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Col.AxisTick");
	}

	public static var AxisBg(get, never):ImPlotCol;

	static inline function get_AxisBg():ImPlotCol {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Col.AxisBg");
	}

	public static var AxisBgHovered(get, never):ImPlotCol;

	static inline function get_AxisBgHovered():ImPlotCol {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Col.AxisBgHovered");
	}

	public static var AxisBgActive(get, never):ImPlotCol;

	static inline function get_AxisBgActive():ImPlotCol {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Col.AxisBgActive");
	}

	public static var Selection(get, never):ImPlotCol;

	static inline function get_Selection():ImPlotCol {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Col.Selection");
	}

	public static var Crosshairs(get, never):ImPlotCol;

	static inline function get_Crosshairs():ImPlotCol {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Col.Crosshairs");
	}

	public static var COUNT(get, never):ImPlotCol;

	static inline function get_COUNT():ImPlotCol {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Col.COUNT");
	}
}

abstract ImPlotColormapScaleFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotColormapScaleFlags;

	static inline function get_None():ImPlotColormapScaleFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.ColormapScaleFlags.None");
	}

	public static var NoLabel(get, never):ImPlotColormapScaleFlags;

	static inline function get_NoLabel():ImPlotColormapScaleFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.ColormapScaleFlags.NoLabel");
	}

	public static var Opposite(get, never):ImPlotColormapScaleFlags;

	static inline function get_Opposite():ImPlotColormapScaleFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.ColormapScaleFlags.Opposite");
	}

	public static var Invert(get, never):ImPlotColormapScaleFlags;

	static inline function get_Invert():ImPlotColormapScaleFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.ColormapScaleFlags.Invert");
	}
}

abstract ImPlotColormap(Int) from Int to Int {
	public static var Deep(get, never):ImPlotColormap;

	static inline function get_Deep():ImPlotColormap {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Colormap.Deep");
	}

	public static var Dark(get, never):ImPlotColormap;

	static inline function get_Dark():ImPlotColormap {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Colormap.Dark");
	}

	public static var Pastel(get, never):ImPlotColormap;

	static inline function get_Pastel():ImPlotColormap {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Colormap.Pastel");
	}

	public static var Paired(get, never):ImPlotColormap;

	static inline function get_Paired():ImPlotColormap {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Colormap.Paired");
	}

	public static var Viridis(get, never):ImPlotColormap;

	static inline function get_Viridis():ImPlotColormap {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Colormap.Viridis");
	}

	public static var Plasma(get, never):ImPlotColormap;

	static inline function get_Plasma():ImPlotColormap {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Colormap.Plasma");
	}

	public static var Hot(get, never):ImPlotColormap;

	static inline function get_Hot():ImPlotColormap {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Colormap.Hot");
	}

	public static var Cool(get, never):ImPlotColormap;

	static inline function get_Cool():ImPlotColormap {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Colormap.Cool");
	}

	public static var Pink(get, never):ImPlotColormap;

	static inline function get_Pink():ImPlotColormap {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Colormap.Pink");
	}

	public static var Jet(get, never):ImPlotColormap;

	static inline function get_Jet():ImPlotColormap {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Colormap.Jet");
	}

	public static var Twilight(get, never):ImPlotColormap;

	static inline function get_Twilight():ImPlotColormap {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Colormap.Twilight");
	}

	public static var RdBu(get, never):ImPlotColormap;

	static inline function get_RdBu():ImPlotColormap {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Colormap.RdBu");
	}

	public static var BrBG(get, never):ImPlotColormap;

	static inline function get_BrBG():ImPlotColormap {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Colormap.BrBG");
	}

	public static var PiYG(get, never):ImPlotColormap;

	static inline function get_PiYG():ImPlotColormap {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Colormap.PiYG");
	}

	public static var Spectral(get, never):ImPlotColormap;

	static inline function get_Spectral():ImPlotColormap {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Colormap.Spectral");
	}

	public static var Greys(get, never):ImPlotColormap;

	static inline function get_Greys():ImPlotColormap {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Colormap.Greys");
	}
}

abstract ImPlotCond(Int) from Int to Int {
	public static var None(get, never):ImPlotCond;

	static inline function get_None():ImPlotCond {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Cond.None");
	}

	public static var Always(get, never):ImPlotCond;

	static inline function get_Always():ImPlotCond {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Cond.Always");
	}

	public static var Once(get, never):ImPlotCond;

	static inline function get_Once():ImPlotCond {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Cond.Once");
	}
}

abstract ImPlotDateFmt(Int) from Int to Int {
	public static var None(get, never):ImPlotDateFmt;

	static inline function get_None():ImPlotDateFmt {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.DateFmt.None");
	}

	public static var DayMo(get, never):ImPlotDateFmt;

	static inline function get_DayMo():ImPlotDateFmt {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.DateFmt.DayMo");
	}

	public static var DayMoYr(get, never):ImPlotDateFmt;

	static inline function get_DayMoYr():ImPlotDateFmt {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.DateFmt.DayMoYr");
	}

	public static var MoYr(get, never):ImPlotDateFmt;

	static inline function get_MoYr():ImPlotDateFmt {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.DateFmt.MoYr");
	}

	public static var Mo(get, never):ImPlotDateFmt;

	static inline function get_Mo():ImPlotDateFmt {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.DateFmt.Mo");
	}

	public static var Yr(get, never):ImPlotDateFmt;

	static inline function get_Yr():ImPlotDateFmt {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.DateFmt.Yr");
	}
}

abstract ImPlotDigitalFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotDigitalFlags;

	static inline function get_None():ImPlotDigitalFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.DigitalFlags.None");
	}
}

abstract ImPlotDragToolFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotDragToolFlags;

	static inline function get_None():ImPlotDragToolFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.DragToolFlags.None");
	}

	public static var NoCursors(get, never):ImPlotDragToolFlags;

	static inline function get_NoCursors():ImPlotDragToolFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.DragToolFlags.NoCursors");
	}

	public static var NoFit(get, never):ImPlotDragToolFlags;

	static inline function get_NoFit():ImPlotDragToolFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.DragToolFlags.NoFit");
	}

	public static var NoInputs(get, never):ImPlotDragToolFlags;

	static inline function get_NoInputs():ImPlotDragToolFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.DragToolFlags.NoInputs");
	}

	public static var Delayed(get, never):ImPlotDragToolFlags;

	static inline function get_Delayed():ImPlotDragToolFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.DragToolFlags.Delayed");
	}
}

abstract ImPlotDummyFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotDummyFlags;

	static inline function get_None():ImPlotDummyFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.DummyFlags.None");
	}
}

abstract ImPlotErrorBarsFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotErrorBarsFlags;

	static inline function get_None():ImPlotErrorBarsFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.ErrorBarsFlags.None");
	}

	public static var Horizontal(get, never):ImPlotErrorBarsFlags;

	static inline function get_Horizontal():ImPlotErrorBarsFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.ErrorBarsFlags.Horizontal");
	}
}

abstract ImPlotFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotFlags;

	static inline function get_None():ImPlotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Flags.None");
	}

	public static var NoTitle(get, never):ImPlotFlags;

	static inline function get_NoTitle():ImPlotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Flags.NoTitle");
	}

	public static var NoLegend(get, never):ImPlotFlags;

	static inline function get_NoLegend():ImPlotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Flags.NoLegend");
	}

	public static var NoMouseText(get, never):ImPlotFlags;

	static inline function get_NoMouseText():ImPlotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Flags.NoMouseText");
	}

	public static var NoInputs(get, never):ImPlotFlags;

	static inline function get_NoInputs():ImPlotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Flags.NoInputs");
	}

	public static var NoMenus(get, never):ImPlotFlags;

	static inline function get_NoMenus():ImPlotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Flags.NoMenus");
	}

	public static var NoBoxSelect(get, never):ImPlotFlags;

	static inline function get_NoBoxSelect():ImPlotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Flags.NoBoxSelect");
	}

	public static var NoFrame(get, never):ImPlotFlags;

	static inline function get_NoFrame():ImPlotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Flags.NoFrame");
	}

	public static var Equal(get, never):ImPlotFlags;

	static inline function get_Equal():ImPlotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Flags.Equal");
	}

	public static var Crosshairs(get, never):ImPlotFlags;

	static inline function get_Crosshairs():ImPlotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Flags.Crosshairs");
	}

	public static var CanvasOnly(get, never):ImPlotFlags;

	static inline function get_CanvasOnly():ImPlotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Flags.CanvasOnly");
	}
}

abstract ImPlotHeatmapFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotHeatmapFlags;

	static inline function get_None():ImPlotHeatmapFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.HeatmapFlags.None");
	}

	public static var ColMajor(get, never):ImPlotHeatmapFlags;

	static inline function get_ColMajor():ImPlotHeatmapFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.HeatmapFlags.ColMajor");
	}
}

abstract ImPlotHistogramFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotHistogramFlags;

	static inline function get_None():ImPlotHistogramFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.HistogramFlags.None");
	}

	public static var Horizontal(get, never):ImPlotHistogramFlags;

	static inline function get_Horizontal():ImPlotHistogramFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.HistogramFlags.Horizontal");
	}

	public static var Cumulative(get, never):ImPlotHistogramFlags;

	static inline function get_Cumulative():ImPlotHistogramFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.HistogramFlags.Cumulative");
	}

	public static var Density(get, never):ImPlotHistogramFlags;

	static inline function get_Density():ImPlotHistogramFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.HistogramFlags.Density");
	}

	public static var NoOutliers(get, never):ImPlotHistogramFlags;

	static inline function get_NoOutliers():ImPlotHistogramFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.HistogramFlags.NoOutliers");
	}

	public static var ColMajor(get, never):ImPlotHistogramFlags;

	static inline function get_ColMajor():ImPlotHistogramFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.HistogramFlags.ColMajor");
	}
}

abstract ImPlotImageFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotImageFlags;

	static inline function get_None():ImPlotImageFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.ImageFlags.None");
	}
}

abstract ImPlotInfLinesFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotInfLinesFlags;

	static inline function get_None():ImPlotInfLinesFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.InfLinesFlags.None");
	}

	public static var Horizontal(get, never):ImPlotInfLinesFlags;

	static inline function get_Horizontal():ImPlotInfLinesFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.InfLinesFlags.Horizontal");
	}
}

abstract ImPlotItemFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotItemFlags;

	static inline function get_None():ImPlotItemFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.ItemFlags.None");
	}

	public static var NoLegend(get, never):ImPlotItemFlags;

	static inline function get_NoLegend():ImPlotItemFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.ItemFlags.NoLegend");
	}

	public static var NoFit(get, never):ImPlotItemFlags;

	static inline function get_NoFit():ImPlotItemFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.ItemFlags.NoFit");
	}
}

abstract ImPlotLegendFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotLegendFlags;

	static inline function get_None():ImPlotLegendFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.LegendFlags.None");
	}

	public static var NoButtons(get, never):ImPlotLegendFlags;

	static inline function get_NoButtons():ImPlotLegendFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.LegendFlags.NoButtons");
	}

	public static var NoHighlightItem(get, never):ImPlotLegendFlags;

	static inline function get_NoHighlightItem():ImPlotLegendFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.LegendFlags.NoHighlightItem");
	}

	public static var NoHighlightAxis(get, never):ImPlotLegendFlags;

	static inline function get_NoHighlightAxis():ImPlotLegendFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.LegendFlags.NoHighlightAxis");
	}

	public static var NoMenus(get, never):ImPlotLegendFlags;

	static inline function get_NoMenus():ImPlotLegendFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.LegendFlags.NoMenus");
	}

	public static var Outside(get, never):ImPlotLegendFlags;

	static inline function get_Outside():ImPlotLegendFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.LegendFlags.Outside");
	}

	public static var Horizontal(get, never):ImPlotLegendFlags;

	static inline function get_Horizontal():ImPlotLegendFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.LegendFlags.Horizontal");
	}

	public static var Sort(get, never):ImPlotLegendFlags;

	static inline function get_Sort():ImPlotLegendFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.LegendFlags.Sort");
	}

	public static var Reverse(get, never):ImPlotLegendFlags;

	static inline function get_Reverse():ImPlotLegendFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.LegendFlags.Reverse");
	}
}

abstract ImPlotLineFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotLineFlags;

	static inline function get_None():ImPlotLineFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.LineFlags.None");
	}

	public static var Segments(get, never):ImPlotLineFlags;

	static inline function get_Segments():ImPlotLineFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.LineFlags.Segments");
	}

	public static var Loop(get, never):ImPlotLineFlags;

	static inline function get_Loop():ImPlotLineFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.LineFlags.Loop");
	}

	public static var SkipNaN(get, never):ImPlotLineFlags;

	static inline function get_SkipNaN():ImPlotLineFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.LineFlags.SkipNaN");
	}

	public static var NoClip(get, never):ImPlotLineFlags;

	static inline function get_NoClip():ImPlotLineFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.LineFlags.NoClip");
	}

	public static var Shaded(get, never):ImPlotLineFlags;

	static inline function get_Shaded():ImPlotLineFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.LineFlags.Shaded");
	}
}

abstract ImPlotLocation(Int) from Int to Int {
	public static var Center(get, never):ImPlotLocation;

	static inline function get_Center():ImPlotLocation {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Location.Center");
	}

	public static var North(get, never):ImPlotLocation;

	static inline function get_North():ImPlotLocation {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Location.North");
	}

	public static var South(get, never):ImPlotLocation;

	static inline function get_South():ImPlotLocation {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Location.South");
	}

	public static var West(get, never):ImPlotLocation;

	static inline function get_West():ImPlotLocation {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Location.West");
	}

	public static var East(get, never):ImPlotLocation;

	static inline function get_East():ImPlotLocation {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Location.East");
	}

	public static var NorthWest(get, never):ImPlotLocation;

	static inline function get_NorthWest():ImPlotLocation {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Location.NorthWest");
	}

	public static var NorthEast(get, never):ImPlotLocation;

	static inline function get_NorthEast():ImPlotLocation {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Location.NorthEast");
	}

	public static var SouthWest(get, never):ImPlotLocation;

	static inline function get_SouthWest():ImPlotLocation {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Location.SouthWest");
	}

	public static var SouthEast(get, never):ImPlotLocation;

	static inline function get_SouthEast():ImPlotLocation {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Location.SouthEast");
	}
}

abstract ImPlotMarkerInternal(Int) from Int to Int {
	public static var Marker_Invalid(get, never):ImPlotMarkerInternal;

	static inline function get_Marker_Invalid():ImPlotMarkerInternal {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.MarkerInternal.Marker_Invalid");
	}
}

abstract ImPlotMarker(Int) from Int to Int {
	public static var None(get, never):ImPlotMarker;

	static inline function get_None():ImPlotMarker {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Marker.None");
	}

	public static var Auto(get, never):ImPlotMarker;

	static inline function get_Auto():ImPlotMarker {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Marker.Auto");
	}

	public static var Circle(get, never):ImPlotMarker;

	static inline function get_Circle():ImPlotMarker {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Marker.Circle");
	}

	public static var Square(get, never):ImPlotMarker;

	static inline function get_Square():ImPlotMarker {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Marker.Square");
	}

	public static var Diamond(get, never):ImPlotMarker;

	static inline function get_Diamond():ImPlotMarker {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Marker.Diamond");
	}

	public static var Up(get, never):ImPlotMarker;

	static inline function get_Up():ImPlotMarker {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Marker.Up");
	}

	public static var Down(get, never):ImPlotMarker;

	static inline function get_Down():ImPlotMarker {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Marker.Down");
	}

	public static var Left(get, never):ImPlotMarker;

	static inline function get_Left():ImPlotMarker {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Marker.Left");
	}

	public static var Right(get, never):ImPlotMarker;

	static inline function get_Right():ImPlotMarker {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Marker.Right");
	}

	public static var Cross(get, never):ImPlotMarker;

	static inline function get_Cross():ImPlotMarker {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Marker.Cross");
	}

	public static var Plus(get, never):ImPlotMarker;

	static inline function get_Plus():ImPlotMarker {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Marker.Plus");
	}

	public static var Asterisk(get, never):ImPlotMarker;

	static inline function get_Asterisk():ImPlotMarker {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Marker.Asterisk");
	}

	public static var COUNT(get, never):ImPlotMarker;

	static inline function get_COUNT():ImPlotMarker {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Marker.COUNT");
	}
}

abstract ImPlotMouseTextFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotMouseTextFlags;

	static inline function get_None():ImPlotMouseTextFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.MouseTextFlags.None");
	}

	public static var NoAuxAxes(get, never):ImPlotMouseTextFlags;

	static inline function get_NoAuxAxes():ImPlotMouseTextFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.MouseTextFlags.NoAuxAxes");
	}

	public static var NoFormat(get, never):ImPlotMouseTextFlags;

	static inline function get_NoFormat():ImPlotMouseTextFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.MouseTextFlags.NoFormat");
	}

	public static var ShowAlways(get, never):ImPlotMouseTextFlags;

	static inline function get_ShowAlways():ImPlotMouseTextFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.MouseTextFlags.ShowAlways");
	}
}

abstract ImPlotPieChartFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotPieChartFlags;

	static inline function get_None():ImPlotPieChartFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.PieChartFlags.None");
	}

	public static var Normalize(get, never):ImPlotPieChartFlags;

	static inline function get_Normalize():ImPlotPieChartFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.PieChartFlags.Normalize");
	}

	public static var IgnoreHidden(get, never):ImPlotPieChartFlags;

	static inline function get_IgnoreHidden():ImPlotPieChartFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.PieChartFlags.IgnoreHidden");
	}

	public static var Exploding(get, never):ImPlotPieChartFlags;

	static inline function get_Exploding():ImPlotPieChartFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.PieChartFlags.Exploding");
	}

	public static var NoSliceBorder(get, never):ImPlotPieChartFlags;

	static inline function get_NoSliceBorder():ImPlotPieChartFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.PieChartFlags.NoSliceBorder");
	}
}

abstract ImPlotPolygonFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotPolygonFlags;

	static inline function get_None():ImPlotPolygonFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.PolygonFlags.None");
	}

	public static var Concave(get, never):ImPlotPolygonFlags;

	static inline function get_Concave():ImPlotPolygonFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.PolygonFlags.Concave");
	}
}

abstract ImPlotProp(Int) from Int to Int {
	public static var LineColor(get, never):ImPlotProp;

	static inline function get_LineColor():ImPlotProp {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Prop.LineColor");
	}

	public static var LineColors(get, never):ImPlotProp;

	static inline function get_LineColors():ImPlotProp {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Prop.LineColors");
	}

	public static var LineWeight(get, never):ImPlotProp;

	static inline function get_LineWeight():ImPlotProp {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Prop.LineWeight");
	}

	public static var FillColor(get, never):ImPlotProp;

	static inline function get_FillColor():ImPlotProp {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Prop.FillColor");
	}

	public static var FillColors(get, never):ImPlotProp;

	static inline function get_FillColors():ImPlotProp {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Prop.FillColors");
	}

	public static var FillAlpha(get, never):ImPlotProp;

	static inline function get_FillAlpha():ImPlotProp {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Prop.FillAlpha");
	}

	public static var Marker(get, never):ImPlotProp;

	static inline function get_Marker():ImPlotProp {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Prop.Marker");
	}

	public static var MarkerSize(get, never):ImPlotProp;

	static inline function get_MarkerSize():ImPlotProp {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Prop.MarkerSize");
	}

	public static var MarkerSizes(get, never):ImPlotProp;

	static inline function get_MarkerSizes():ImPlotProp {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Prop.MarkerSizes");
	}

	public static var MarkerLineColor(get, never):ImPlotProp;

	static inline function get_MarkerLineColor():ImPlotProp {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Prop.MarkerLineColor");
	}

	public static var MarkerLineColors(get, never):ImPlotProp;

	static inline function get_MarkerLineColors():ImPlotProp {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Prop.MarkerLineColors");
	}

	public static var MarkerFillColor(get, never):ImPlotProp;

	static inline function get_MarkerFillColor():ImPlotProp {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Prop.MarkerFillColor");
	}

	public static var MarkerFillColors(get, never):ImPlotProp;

	static inline function get_MarkerFillColors():ImPlotProp {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Prop.MarkerFillColors");
	}

	public static var Size(get, never):ImPlotProp;

	static inline function get_Size():ImPlotProp {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Prop.Size");
	}

	public static var Offset(get, never):ImPlotProp;

	static inline function get_Offset():ImPlotProp {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Prop.Offset");
	}

	public static var Stride(get, never):ImPlotProp;

	static inline function get_Stride():ImPlotProp {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Prop.Stride");
	}

	public static var Flags(get, never):ImPlotProp;

	static inline function get_Flags():ImPlotProp {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Prop.Flags");
	}
}

abstract ImPlotScale(Int) from Int to Int {
	public static var Linear(get, never):ImPlotScale;

	static inline function get_Linear():ImPlotScale {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Scale.Linear");
	}

	public static var Time(get, never):ImPlotScale;

	static inline function get_Time():ImPlotScale {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Scale.Time");
	}

	public static var Log10(get, never):ImPlotScale;

	static inline function get_Log10():ImPlotScale {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Scale.Log10");
	}

	public static var SymLog(get, never):ImPlotScale;

	static inline function get_SymLog():ImPlotScale {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.Scale.SymLog");
	}
}

abstract ImPlotScatterFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotScatterFlags;

	static inline function get_None():ImPlotScatterFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.ScatterFlags.None");
	}

	public static var NoClip(get, never):ImPlotScatterFlags;

	static inline function get_NoClip():ImPlotScatterFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.ScatterFlags.NoClip");
	}
}

abstract ImPlotShadedFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotShadedFlags;

	static inline function get_None():ImPlotShadedFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.ShadedFlags.None");
	}
}

abstract ImPlotStairsFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotStairsFlags;

	static inline function get_None():ImPlotStairsFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StairsFlags.None");
	}

	public static var PreStep(get, never):ImPlotStairsFlags;

	static inline function get_PreStep():ImPlotStairsFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StairsFlags.PreStep");
	}

	public static var Shaded(get, never):ImPlotStairsFlags;

	static inline function get_Shaded():ImPlotStairsFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StairsFlags.Shaded");
	}
}

abstract ImPlotStemsFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotStemsFlags;

	static inline function get_None():ImPlotStemsFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StemsFlags.None");
	}

	public static var Horizontal(get, never):ImPlotStemsFlags;

	static inline function get_Horizontal():ImPlotStemsFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StemsFlags.Horizontal");
	}
}

abstract ImPlotStyleVar(Int) from Int to Int {
	public static var PlotDefaultSize(get, never):ImPlotStyleVar;

	static inline function get_PlotDefaultSize():ImPlotStyleVar {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StyleVar.PlotDefaultSize");
	}

	public static var PlotMinSize(get, never):ImPlotStyleVar;

	static inline function get_PlotMinSize():ImPlotStyleVar {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StyleVar.PlotMinSize");
	}

	public static var PlotBorderSize(get, never):ImPlotStyleVar;

	static inline function get_PlotBorderSize():ImPlotStyleVar {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StyleVar.PlotBorderSize");
	}

	public static var MinorAlpha(get, never):ImPlotStyleVar;

	static inline function get_MinorAlpha():ImPlotStyleVar {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StyleVar.MinorAlpha");
	}

	public static var MajorTickLen(get, never):ImPlotStyleVar;

	static inline function get_MajorTickLen():ImPlotStyleVar {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StyleVar.MajorTickLen");
	}

	public static var MinorTickLen(get, never):ImPlotStyleVar;

	static inline function get_MinorTickLen():ImPlotStyleVar {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StyleVar.MinorTickLen");
	}

	public static var MajorTickSize(get, never):ImPlotStyleVar;

	static inline function get_MajorTickSize():ImPlotStyleVar {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StyleVar.MajorTickSize");
	}

	public static var MinorTickSize(get, never):ImPlotStyleVar;

	static inline function get_MinorTickSize():ImPlotStyleVar {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StyleVar.MinorTickSize");
	}

	public static var MajorGridSize(get, never):ImPlotStyleVar;

	static inline function get_MajorGridSize():ImPlotStyleVar {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StyleVar.MajorGridSize");
	}

	public static var MinorGridSize(get, never):ImPlotStyleVar;

	static inline function get_MinorGridSize():ImPlotStyleVar {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StyleVar.MinorGridSize");
	}

	public static var PlotPadding(get, never):ImPlotStyleVar;

	static inline function get_PlotPadding():ImPlotStyleVar {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StyleVar.PlotPadding");
	}

	public static var LabelPadding(get, never):ImPlotStyleVar;

	static inline function get_LabelPadding():ImPlotStyleVar {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StyleVar.LabelPadding");
	}

	public static var LegendPadding(get, never):ImPlotStyleVar;

	static inline function get_LegendPadding():ImPlotStyleVar {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StyleVar.LegendPadding");
	}

	public static var LegendInnerPadding(get, never):ImPlotStyleVar;

	static inline function get_LegendInnerPadding():ImPlotStyleVar {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StyleVar.LegendInnerPadding");
	}

	public static var LegendSpacing(get, never):ImPlotStyleVar;

	static inline function get_LegendSpacing():ImPlotStyleVar {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StyleVar.LegendSpacing");
	}

	public static var MousePosPadding(get, never):ImPlotStyleVar;

	static inline function get_MousePosPadding():ImPlotStyleVar {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StyleVar.MousePosPadding");
	}

	public static var AnnotationPadding(get, never):ImPlotStyleVar;

	static inline function get_AnnotationPadding():ImPlotStyleVar {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StyleVar.AnnotationPadding");
	}

	public static var FitPadding(get, never):ImPlotStyleVar;

	static inline function get_FitPadding():ImPlotStyleVar {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StyleVar.FitPadding");
	}

	public static var DigitalPadding(get, never):ImPlotStyleVar;

	static inline function get_DigitalPadding():ImPlotStyleVar {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StyleVar.DigitalPadding");
	}

	public static var DigitalSpacing(get, never):ImPlotStyleVar;

	static inline function get_DigitalSpacing():ImPlotStyleVar {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StyleVar.DigitalSpacing");
	}

	public static var COUNT(get, never):ImPlotStyleVar;

	static inline function get_COUNT():ImPlotStyleVar {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.StyleVar.COUNT");
	}
}

abstract ImPlotSubplotFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotSubplotFlags;

	static inline function get_None():ImPlotSubplotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.SubplotFlags.None");
	}

	public static var NoTitle(get, never):ImPlotSubplotFlags;

	static inline function get_NoTitle():ImPlotSubplotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.SubplotFlags.NoTitle");
	}

	public static var NoLegend(get, never):ImPlotSubplotFlags;

	static inline function get_NoLegend():ImPlotSubplotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.SubplotFlags.NoLegend");
	}

	public static var NoMenus(get, never):ImPlotSubplotFlags;

	static inline function get_NoMenus():ImPlotSubplotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.SubplotFlags.NoMenus");
	}

	public static var NoResize(get, never):ImPlotSubplotFlags;

	static inline function get_NoResize():ImPlotSubplotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.SubplotFlags.NoResize");
	}

	public static var NoAlign(get, never):ImPlotSubplotFlags;

	static inline function get_NoAlign():ImPlotSubplotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.SubplotFlags.NoAlign");
	}

	public static var ShareItems(get, never):ImPlotSubplotFlags;

	static inline function get_ShareItems():ImPlotSubplotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.SubplotFlags.ShareItems");
	}

	public static var LinkRows(get, never):ImPlotSubplotFlags;

	static inline function get_LinkRows():ImPlotSubplotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.SubplotFlags.LinkRows");
	}

	public static var LinkCols(get, never):ImPlotSubplotFlags;

	static inline function get_LinkCols():ImPlotSubplotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.SubplotFlags.LinkCols");
	}

	public static var LinkAllX(get, never):ImPlotSubplotFlags;

	static inline function get_LinkAllX():ImPlotSubplotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.SubplotFlags.LinkAllX");
	}

	public static var LinkAllY(get, never):ImPlotSubplotFlags;

	static inline function get_LinkAllY():ImPlotSubplotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.SubplotFlags.LinkAllY");
	}

	public static var ColMajor(get, never):ImPlotSubplotFlags;

	static inline function get_ColMajor():ImPlotSubplotFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.SubplotFlags.ColMajor");
	}
}

abstract ImPlotTextFlags(Int) from Int to Int {
	public static var None(get, never):ImPlotTextFlags;

	static inline function get_None():ImPlotTextFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.TextFlags.None");
	}

	public static var Vertical(get, never):ImPlotTextFlags;

	static inline function get_Vertical():ImPlotTextFlags {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.TextFlags.Vertical");
	}
}

abstract ImPlotTimeFmt(Int) from Int to Int {
	public static var None(get, never):ImPlotTimeFmt;

	static inline function get_None():ImPlotTimeFmt {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.TimeFmt.None");
	}

	public static var Us(get, never):ImPlotTimeFmt;

	static inline function get_Us():ImPlotTimeFmt {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.TimeFmt.Us");
	}

	public static var SUs(get, never):ImPlotTimeFmt;

	static inline function get_SUs():ImPlotTimeFmt {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.TimeFmt.SUs");
	}

	public static var SMs(get, never):ImPlotTimeFmt;

	static inline function get_SMs():ImPlotTimeFmt {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.TimeFmt.SMs");
	}

	public static var S(get, never):ImPlotTimeFmt;

	static inline function get_S():ImPlotTimeFmt {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.TimeFmt.S");
	}

	public static var MinSMs(get, never):ImPlotTimeFmt;

	static inline function get_MinSMs():ImPlotTimeFmt {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.TimeFmt.MinSMs");
	}

	public static var HrMinSMs(get, never):ImPlotTimeFmt;

	static inline function get_HrMinSMs():ImPlotTimeFmt {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.TimeFmt.HrMinSMs");
	}

	public static var HrMinS(get, never):ImPlotTimeFmt;

	static inline function get_HrMinS():ImPlotTimeFmt {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.TimeFmt.HrMinS");
	}

	public static var HrMin(get, never):ImPlotTimeFmt;

	static inline function get_HrMin():ImPlotTimeFmt {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.TimeFmt.HrMin");
	}

	public static var Hr(get, never):ImPlotTimeFmt;

	static inline function get_Hr():ImPlotTimeFmt {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.TimeFmt.Hr");
	}
}

abstract ImPlotTimeUnit(Int) from Int to Int {
	public static var Us(get, never):ImPlotTimeUnit;

	static inline function get_Us():ImPlotTimeUnit {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.TimeUnit.Us");
	}

	public static var Ms(get, never):ImPlotTimeUnit;

	static inline function get_Ms():ImPlotTimeUnit {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.TimeUnit.Ms");
	}

	public static var S(get, never):ImPlotTimeUnit;

	static inline function get_S():ImPlotTimeUnit {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.TimeUnit.S");
	}

	public static var Min(get, never):ImPlotTimeUnit;

	static inline function get_Min():ImPlotTimeUnit {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.TimeUnit.Min");
	}

	public static var Hr(get, never):ImPlotTimeUnit;

	static inline function get_Hr():ImPlotTimeUnit {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.TimeUnit.Hr");
	}

	public static var Day(get, never):ImPlotTimeUnit;

	static inline function get_Day():ImPlotTimeUnit {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.TimeUnit.Day");
	}

	public static var Mo(get, never):ImPlotTimeUnit;

	static inline function get_Mo():ImPlotTimeUnit {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.TimeUnit.Mo");
	}

	public static var Yr(get, never):ImPlotTimeUnit;

	static inline function get_Yr():ImPlotTimeUnit {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.TimeUnit.Yr");
	}

	public static var COUNT(get, never):ImPlotTimeUnit;

	static inline function get_COUNT():ImPlotTimeUnit {
		return cast js.Syntax.code("globalThis.__imguiHxJsImGui.ImPlot.TimeUnit.COUNT");
	}
}

@:keep @:native("globalThis.__imguiHxJsImGui.ImPlotDateTimeSpec") extern class ImPlotDateTimeSpec extends imguijs.ImGui.ValueStruct {
	@:native("Date")
	var date:Float;
	@:native("Time")
	var time:Float;
	@:native("UseISO8601")
	var useISO8601:Bool;
	@:native("Use24HourClock")
	var use24HourClock:Bool;
	function new(?Date:Float, ?Time:Float, ?UseISO8601:Bool, ?Use24HourClock:Bool);
	static function From(obj:ImPlotDateTimeSpec):ImPlotDateTimeSpec;
}
@:keep @:native("globalThis.__imguiHxJsImGui.ImPlotPoint") extern class ImPlotPoint extends imguijs.ImGui.ValueStruct {
	var x:Float;
	var y:Float;
	function new(?x:Float, ?y:Float);
	static function From(obj:ImPlotPoint):ImPlotPoint;
}
@:keep @:native("globalThis.__imguiHxJsImGui.ImPlotRange") extern class ImPlotRange extends imguijs.ImGui.ValueStruct {
	@:native("Min")
	var min:Float;
	@:native("Max")
	var max:Float;
	function new(?Min:Float, ?Max:Float);
	static function From(obj:ImPlotRange):ImPlotRange;
}
@:keep @:native("globalThis.__imguiHxJsImGui.ImPlotRect") extern class ImPlotRect extends imguijs.ImGui.ValueStruct {
	@:native("X")
	var x:ImPlotRange;
	@:native("Y")
	var y:ImPlotRange;
	function new(?X:ImPlotRange, ?Y:ImPlotRange);
	static function From(obj:ImPlotRect):ImPlotRect;
}
@:keep @:native("globalThis.__imguiHxJsImGui.ImPlotTime") extern class ImPlotTime extends imguijs.ImGui.ValueStruct {
	@:native("S")
	var s:Float;
	@:native("Us")
	var us:Float;
	function new(?S:Float, ?Us:Float);
	static function From(obj:ImPlotTime):ImPlotTime;
}
@:keep @:native("globalThis.__imguiHxJsImGui.ImPlotSpec") extern class ImPlotSpec extends imguijs.ImGui.ValueStruct {
	@:native("LineColor")
	var lineColor:imguijs.Abstracts.ImVec4;
	@:native("LineWeight")
	var lineWeight:Float;
	@:native("FillColor")
	var fillColor:imguijs.Abstracts.ImVec4;
	@:native("FillAlpha")
	var fillAlpha:Float;
	@:native("Marker")
	var marker:Float;
	@:native("MarkerSize")
	var markerSize:Float;
	@:native("MarkerLineColor")
	var markerLineColor:imguijs.Abstracts.ImVec4;
	@:native("MarkerFillColor")
	var markerFillColor:imguijs.Abstracts.ImVec4;
	@:native("Size")
	var size:Float;
	@:native("Offset")
	var offset:Float;
	@:native("Stride")
	var stride:Float;
	@:native("Flags")
	var flags:Float;
	function new(?LineColor:imguijs.Abstracts.ImVec4, ?LineWeight:Float, ?FillColor:imguijs.Abstracts.ImVec4, ?FillAlpha:Float, ?Marker:Float, ?MarkerSize:Float, ?MarkerLineColor:imguijs.Abstracts.ImVec4, ?MarkerFillColor:imguijs.Abstracts.ImVec4, ?Size:Float, ?Offset:Float, ?Stride:Float, ?Flags:Float);
	static function From(obj:ImPlotSpec):ImPlotSpec;
}
@:keep @:native("globalThis.__imguiHxJsImGui.ImPlot") extern class ImPlot {
	static var Auto:Float;
	@:native("AddColormap_U32Ptr")
	static function addColormap_U32Ptr(name:String, cols:Array<Float>, size:Float, ?qual:Bool):Float;
	@:native("AddColormap_Vec4Ptr")
	static function addColormap_Vec4Ptr(name:String, cols:Array<imguijs.Abstracts.ImVec4>, size:Float, ?qual:Bool):Float;
	@:native("Annotation_Bool")
	static function annotation_Bool(x:Float, y:Float, col:imguijs.Abstracts.ImVec4, pix_offset:imguijs.Abstracts.ImVec2, clamp:Bool, ?round:Bool):Void;
	@:native("BeginAlignedPlots")
	static function beginAlignedPlots(group_id:String, ?vertical:Bool):Bool;
	@:native("BeginDragDropSourceAxis")
	static function beginDragDropSourceAxis(axis:Float, ?flags:Float):Bool;
	@:native("BeginDragDropSourceItem")
	static function beginDragDropSourceItem(label_id:String, ?flags:Float):Bool;
	@:native("BeginDragDropSourcePlot")
	static function beginDragDropSourcePlot(?flags:Float):Bool;
	@:native("BeginDragDropTargetAxis")
	static function beginDragDropTargetAxis(axis:Float):Bool;
	@:native("BeginDragDropTargetLegend")
	static function beginDragDropTargetLegend():Bool;
	@:native("BeginDragDropTargetPlot")
	static function beginDragDropTargetPlot():Bool;
	@:native("BeginLegendPopup")
	static function beginLegendPopup(label_id:String, ?mouse_button:Float):Bool;
	@:native("BeginPlot")
	static function beginPlot(title_id:String, ?size:imguijs.Abstracts.ImVec2, ?flags:Float):Bool;
	@:native("BeginSubplots")
	static function beginSubplots(title_id:String, rows:Float, cols:Float, size:imguijs.Abstracts.ImVec2, ?flags:Float, ?row_ratios:Array<Float>, ?col_ratios:Array<Float>):Bool;
	@:native("BustColorCache")
	static function bustColorCache(?plot_title_id:String):Void;
	@:native("CancelPlotSelection")
	static function cancelPlotSelection():Void;
	@:native("ColormapButton")
	static function colormapButton(label:String, ?size:imguijs.Abstracts.ImVec2, ?cmap:Float):Bool;
	@:native("ColormapIcon")
	static function colormapIcon(cmap:Float):Void;
	@:native("ColormapScale")
	static function colormapScale(label:String, scale_min:Float, scale_max:Float, ?size:imguijs.Abstracts.ImVec2, ?format:String, ?flags:Float, ?cmap:Float):Void;
	@:native("ColormapSlider")
	static function colormapSlider(label:String, t:Array<Float>, ?out:Array<imguijs.Abstracts.ImVec4>, ?format:String, ?cmap:Float):Bool;
	@:native("CreateContext")
	static function createContext():Float;
	@:native("DestroyContext")
	static function destroyContext(?ctx:Float):Void;
	@:native("EndAlignedPlots")
	static function endAlignedPlots():Void;
	@:native("EndDragDropSource")
	static function endDragDropSource():Void;
	@:native("EndDragDropTarget")
	static function endDragDropTarget():Void;
	@:native("EndLegendPopup")
	static function endLegendPopup():Void;
	@:native("EndPlot")
	static function endPlot():Void;
	@:native("EndSubplots")
	static function endSubplots():Void;
	@:native("GetColormapColor")
	static function getColormapColor(idx:Float, ?cmap:Float):imguijs.Abstracts.ImVec4;
	@:native("GetColormapCount")
	static function getColormapCount():Float;
	@:native("GetColormapIndex")
	static function getColormapIndex(name:String):Float;
	@:native("GetColormapSize")
	static function getColormapSize(?cmap:Float):Float;
	@:native("GetCurrentContext")
	static function getCurrentContext():Float;
	@:native("GetInputMap")
	static function getInputMap():Float;
	@:native("GetLastItemColor")
	static function getLastItemColor():imguijs.Abstracts.ImVec4;
	@:native("GetPlotLimits")
	static function getPlotLimits(?x_axis:Float, ?y_axis:Float):ImPlotRect;
	@:native("GetPlotMousePos")
	static function getPlotMousePos(?x_axis:Float, ?y_axis:Float):ImPlotPoint;
	@:native("GetPlotPos")
	static function getPlotPos():imguijs.Abstracts.ImVec2;
	@:native("GetPlotSelection")
	static function getPlotSelection(?x_axis:Float, ?y_axis:Float):ImPlotRect;
	@:native("GetPlotSize")
	static function getPlotSize():imguijs.Abstracts.ImVec2;
	@:native("GetStyle")
	static function getStyle():Float;
	@:native("HideNextItem")
	static function hideNextItem(?hidden:Bool, ?cond:Float):Void;
	@:native("IsAxisHovered")
	static function isAxisHovered(axis:Float):Bool;
	@:native("IsLegendEntryHovered")
	static function isLegendEntryHovered(label_id:String):Bool;
	@:native("IsPlotHovered")
	static function isPlotHovered():Bool;
	@:native("IsPlotSelected")
	static function isPlotSelected():Bool;
	@:native("IsSubplotsHovered")
	static function isSubplotsHovered():Bool;
	@:native("ItemIcon_U32")
	static function itemIcon_U32(col:Float):Void;
	@:native("ItemIcon_Vec4")
	static function itemIcon_Vec4(col:imguijs.Abstracts.ImVec4):Void;
	@:native("MapInputDefault")
	static function mapInputDefault(?dst:Float):Void;
	@:native("MapInputReverse")
	static function mapInputReverse(?dst:Float):Void;
	@:native("NextColormapColor")
	static function nextColormapColor():imguijs.Abstracts.ImVec4;
	@:native("NextMarker")
	static function nextMarker():Float;
	@:native("PixelsToPlot")
	static function pixelsToPlot(x:Float, y:Float, ?x_axis:Float, ?y_axis:Float):ImPlotPoint;
	@:native("PixelsToPlotVec2")
	static function pixelsToPlotVec2(pix:imguijs.Abstracts.ImVec2, ?x_axis:Float, ?y_axis:Float):ImPlotPoint;
	@:native("PlotBarGroups")
	static function plotBarGroups(label_ids:Null<Array<String>>, values:Array<Float>, item_count:Float, group_count:Float, ?group_size:Float, ?shift:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotBarsXY")
	static function plotBarsXY(label_id:String, xs:Array<Float>, ys:Array<Float>, count:Float, bar_size:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotBars")
	static function plotBars(label_id:String, values:Array<Float>, count:Float, ?bar_size:Float, ?shift:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotBubblesXY")
	static function plotBubblesXY(label_id:String, xs:Array<Float>, ys:Array<Float>, szs:Array<Float>, count:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotBubbles")
	static function plotBubbles(label_id:String, values:Array<Float>, szs:Array<Float>, count:Float, ?xscale:Float, ?xstart:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotDigital")
	static function plotDigital(label_id:String, xs:Array<Float>, ys:Array<Float>, count:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotDummy")
	static function plotDummy(label_id:String, ?spec:ImPlotSpec):Void;
	@:native("PlotErrorBarsRange")
	static function plotErrorBarsRange(label_id:String, xs:Array<Float>, ys:Array<Float>, neg:Array<Float>, pos:Array<Float>, count:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotErrorBars")
	static function plotErrorBars(label_id:String, xs:Array<Float>, ys:Array<Float>, err:Array<Float>, count:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotHeatmap")
	static function plotHeatmap(label_id:String, values:Array<Float>, rows:Float, cols:Float, ?scale_min:Float, ?scale_max:Float, ?label_fmt:String, ?bounds_min:ImPlotPoint, ?bounds_max:ImPlotPoint, ?spec:ImPlotSpec):Void;
	@:native("PlotHistogram")
	static function plotHistogram(label_id:String, values:Array<Float>, count:Float, ?bins:Float, ?bar_scale:Float, ?range:ImPlotRange, ?spec:ImPlotSpec):Float;
	@:native("PlotHistogram2D")
	static function plotHistogram2D(label_id:String, xs:Array<Float>, ys:Array<Float>, count:Float, ?x_bins:Float, ?y_bins:Float, ?range:ImPlotRect, ?spec:ImPlotSpec):Float;
	@:native("PlotInfLines")
	static function plotInfLines(label_id:String, values:Array<Float>, count:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotLineXY")
	static function plotLineXY(label_id:String, xs:Array<Float>, ys:Array<Float>, count:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotLine")
	static function plotLine(label_id:String, values:Array<Float>, count:Float, ?xscale:Float, ?xstart:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotPieChart")
	static function plotPieChart(label_ids:Null<Array<String>>, values:Array<Float>, count:Float, x:Float, y:Float, radius:Float, ?label_fmt:String, ?angle0:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotPolygon")
	static function plotPolygon(label_id:String, xs:Array<Float>, ys:Array<Float>, count:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotScatterXY")
	static function plotScatterXY(label_id:String, xs:Array<Float>, ys:Array<Float>, count:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotScatter")
	static function plotScatter(label_id:String, values:Array<Float>, count:Float, ?xscale:Float, ?xstart:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotShadedBand")
	static function plotShadedBand(label_id:String, xs:Array<Float>, ys1:Array<Float>, ys2:Array<Float>, count:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotShadedXY")
	static function plotShadedXY(label_id:String, xs:Array<Float>, ys:Array<Float>, count:Float, ?yref:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotShaded")
	static function plotShaded(label_id:String, values:Array<Float>, count:Float, ?yref:Float, ?xscale:Float, ?xstart:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotStairsXY")
	static function plotStairsXY(label_id:String, xs:Array<Float>, ys:Array<Float>, count:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotStairs")
	static function plotStairs(label_id:String, values:Array<Float>, count:Float, ?xscale:Float, ?xstart:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotStemsXY")
	static function plotStemsXY(label_id:String, xs:Array<Float>, ys:Array<Float>, count:Float, ?ref:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotStems")
	static function plotStems(label_id:String, values:Array<Float>, count:Float, ?ref:Float, ?scale:Float, ?start:Float, ?spec:ImPlotSpec):Void;
	@:native("PlotText")
	static function plotText(text:String, x:Float, y:Float, ?pix_offset:imguijs.Abstracts.ImVec2, ?spec:ImPlotSpec):Void;
	@:native("PlotToPixels")
	static function plotToPixels(x:Float, y:Float, ?x_axis:Float, ?y_axis:Float):imguijs.Abstracts.ImVec2;
	@:native("PlotToPixelsPoint")
	static function plotToPixelsPoint(plt:ImPlotPoint, ?x_axis:Float, ?y_axis:Float):imguijs.Abstracts.ImVec2;
	@:native("PopColormap")
	static function popColormap(?count:Float):Void;
	@:native("PopPlotClipRect")
	static function popPlotClipRect():Void;
	@:native("PopStyleColor")
	static function popStyleColor(?count:Float):Void;
	@:native("PopStyleVar")
	static function popStyleVar(?count:Float):Void;
	@:native("PushColormap_PlotColormap")
	static function pushColormap_PlotColormap(cmap:Float):Void;
	@:native("PushColormap_Str")
	static function pushColormap_Str(name:String):Void;
	@:native("PushPlotClipRect")
	static function pushPlotClipRect(?expand:Float):Void;
	@:native("PushStyleColor_U32")
	static function pushStyleColor_U32(idx:Float, col:Float):Void;
	@:native("PushStyleColor_Vec4")
	static function pushStyleColor_Vec4(idx:Float, col:imguijs.Abstracts.ImVec4):Void;
	@:native("PushStyleVar_Float")
	static function pushStyleVar_Float(idx:Float, val:Float):Void;
	@:native("PushStyleVar_Int")
	static function pushStyleVar_Int(idx:Float, val:Float):Void;
	@:native("PushStyleVar_Vec2")
	static function pushStyleVar_Vec2(idx:Float, val:imguijs.Abstracts.ImVec2):Void;
	@:native("SampleColormap")
	static function sampleColormap(t:Float, ?cmap:Float):imguijs.Abstracts.ImVec4;
	@:native("SetAxes")
	static function setAxes(x_axis:Float, y_axis:Float):Void;
	@:native("SetAxis")
	static function setAxis(axis:Float):Void;
	@:native("SetCurrentContext")
	static function setCurrentContext(ctx:Float):Void;
	@:native("SetImGuiContext")
	static function setImGuiContext(ctx:Float):Void;
	@:native("SetNextAxesLimits")
	static function setNextAxesLimits(x_min:Float, x_max:Float, y_min:Float, y_max:Float, ?cond:Float):Void;
	@:native("SetNextAxesToFit")
	static function setNextAxesToFit():Void;
	@:native("SetNextAxisLimits")
	static function setNextAxisLimits(axis:Float, v_min:Float, v_max:Float, ?cond:Float):Void;
	@:native("SetNextAxisLinks")
	static function setNextAxisLinks(axis:Float, link_min:Array<Float>, link_max:Array<Float>):Void;
	@:native("SetNextAxisToFit")
	static function setNextAxisToFit(axis:Float):Void;
	@:native("SetupAxes")
	static function setupAxes(x_label:String, y_label:String, ?x_flags:Float, ?y_flags:Float):Void;
	@:native("SetupAxesLimits")
	static function setupAxesLimits(x_min:Float, x_max:Float, y_min:Float, y_max:Float, ?cond:Float):Void;
	@:native("SetupAxis")
	static function setupAxis(axis:Float, ?label:String, ?flags:Float):Void;
	@:native("SetupAxisFormat_Str")
	static function setupAxisFormat_Str(axis:Float, fmt:String):Void;
	@:native("SetupAxisLimits")
	static function setupAxisLimits(axis:Float, v_min:Float, v_max:Float, ?cond:Float):Void;
	@:native("SetupAxisLimitsConstraints")
	static function setupAxisLimitsConstraints(axis:Float, v_min:Float, v_max:Float):Void;
	@:native("SetupAxisLinks")
	static function setupAxisLinks(axis:Float, link_min:Array<Float>, link_max:Array<Float>):Void;
	@:native("SetupAxisScale_PlotScale")
	static function setupAxisScale_PlotScale(axis:Float, scale:Float):Void;
	@:native("SetupAxisTicksRange")
	static function setupAxisTicksRange(axis:Float, v_min:Float, v_max:Float, n_ticks:Float, ?labels:Array<String>, ?keep_default:Bool):Void;
	@:native("SetupAxisTicks")
	static function setupAxisTicks(axis:Float, values:Array<Float>, n_ticks:Float, ?labels:Array<String>, ?keep_default:Bool):Void;
	@:native("SetupAxisZoomConstraints")
	static function setupAxisZoomConstraints(axis:Float, z_min:Float, z_max:Float):Void;
	@:native("SetupFinish")
	static function setupFinish():Void;
	@:native("SetupLegend")
	static function setupLegend(location:Float, ?flags:Float):Void;
	@:native("SetupMouseText")
	static function setupMouseText(location:Float, ?flags:Float):Void;
	@:native("ShowColormapSelector")
	static function showColormapSelector(label:String):Bool;
	@:native("ShowInputMapSelector")
	static function showInputMapSelector(label:String):Bool;
	@:native("ShowStyleEditor")
	static function showStyleEditor(?ref:Float):Void;
	@:native("ShowStyleSelector")
	static function showStyleSelector(label:String):Bool;
	@:native("ShowUserGuide")
	static function showUserGuide():Void;
	@:native("StyleColorsAuto")
	static function styleColorsAuto(?dst:Float):Void;
	@:native("StyleColorsClassic")
	static function styleColorsClassic(?dst:Float):Void;
	@:native("StyleColorsDark")
	static function styleColorsDark(?dst:Float):Void;
	@:native("StyleColorsLight")
	static function styleColorsLight(?dst:Float):Void;
	@:native("TagX_Bool")
	static function tagX_Bool(x:Float, col:imguijs.Abstracts.ImVec4, ?round:Bool):Void;
	@:native("TagY_Bool")
	static function tagY_Bool(y:Float, col:imguijs.Abstracts.ImVec4, ?round:Bool):Void;
	@:native("InputMap_destroy")
	static function inputMap_destroy(self:Float):Void;
	@:native("InputMap_ImPlotInputMap")
	static function inputMap_ImPlotInputMap():Float;
	@:native("Style_destroy")
	static function style_destroy(self:Float):Void;
	@:native("Style_ImPlotStyle")
	static function style_ImPlotStyle():Float;
}

#end
