package imguijs;

#if js
/**
	Generated by `tools/generate-jsimgui-externs.mjs` from
	`node_modules/@mori2003/jsimgui/build/*.d.ts`.
**/
@:native("globalThis.__imguiHxJsImGui")
extern class Module {
	static var ImColor:Dynamic;
	static var ImDrawCmd:Dynamic;
	static var ImDrawData:Dynamic;
	static var ImDrawList:Dynamic;
	static var ImDrawListSharedData:Dynamic;
	static var ImFont:Dynamic;
	static var ImFontAtlas:Dynamic;
	static var ImFontAtlasBuilder:Dynamic;
	static var ImFontAtlasRect:Dynamic;
	static var ImFontBaked:Dynamic;
	static var ImFontConfig:Dynamic;
	static var ImFontLoader:Dynamic;
	static var ImGui:Dynamic;
	static var ImGuiContext:Dynamic;
	static var ImGuiImplOpenGL3:Dynamic;
	static var ImGuiImplWeb:Dynamic;
	static var ImGuiImplWGPU:Dynamic;
	static var ImGuiInputTextCallbackData:Dynamic;
	static var ImGuiIO:Dynamic;
	static var ImGuiListClipper:Dynamic;
	static var ImGuiMultiSelectIO:Dynamic;
	static var ImGuiPayload:Dynamic;
	static var ImGuiPlatformIO:Dynamic;
	static var ImGuiSizeCallbackData:Dynamic;
	static var ImGuiStyle:Dynamic;
	static var ImGuiTableColumnSortSpecs:Dynamic;
	static var ImGuiTableSortSpecs:Dynamic;
	static var ImGuiViewport:Dynamic;
	static var ImGuiWindowClass:Dynamic;
	static var ImTextureRef:Dynamic;
	static var ImVec2:Dynamic;
	static var ImVec4:Dynamic;
	static var State:Dynamic;
}
#end
